################# TIME #################

- alias: 'Evening bright'
  initial_state: on
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    condition: state
    entity_id: group.device_tracker_family
    state: 'home'
  action:
    - service: scene.turn_on
      entity_id: scene.vardagsrum_bright
    - service: scene.turn_on
      entity_id: scene.sovrum_bright
    - service: scene.turn_on
      entity_id: scene.hall_bright

- alias: 'Evening relaxed'
  initial_state: on
  trigger:
    platform: time
    at: '21:30:00'
  condition:
    condition: state
    entity_id: group.device_tracker_family
    state: 'home'
  action:
    - service: scene.turn_on
      entity_id: scene.vardagsrum_relaxed
    - service: scene.turn_on
      entity_id: scene.sovrum_relaxed
    - service: scene.turn_on
      entity_id: scene.hall_relaxed

- alias: 'Morning not home'
  initial_state: on
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.device_tracker_family
        state: 'not_home'
      - condition: state
        entity_id: group.all_lights
        state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.all_lights_off

################# WAKEUP #################

- alias: 'Wakeup weekdays'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.alarm_clock_trigger_weekdays
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.wakeup_override
        state: 'on'
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
          - condition: state
            entity_id: group.device_tracker_family
            state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.wakeup

- alias: 'Wakeup weekend'
  initial_state: off
  trigger:
    platform: state
    entity_id: binary_sensor.alarm_clock_trigger_weekend
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sat
          - sun
      - condition: state
        entity_id: group.device_tracker_family
        state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.wakeup

################# SONOS #################

- alias: 'Enable Sonos alarm'
  initial_state: on
  trigger:
    platform: time
    at: '03:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: group.device_tracker_family
        state: 'home'
      - condition: state
        entity_id: automation.wakeup_weekdays
        state: 'on'
  action:
    service: script.sonos_set_alarm

#- alias: 'Disable Sonos alarm'
#  initial_state: off
#  trigger:
#    platform: time
#    at: '03:00:00'
#  condition:
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: binary_sensor.workday_sensor
#       state: 'off'
#     - condition: state
#        entity_id: group.device_tracker_family
#        state: 'not_home'
#      - condition: state
#        entity_id: automation.wakeup_weekdays
#        state: 'off'
# action:
#    service: script.sonos_disable_alarm

- alias: 'Coming home group Sonos speakers'
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.device_tracker_family
      to: 'home'
  condition:
    condition: state
    entity_id: media_player.tv
    state: 'off'
  action:
    - service: script.sonos_group_speakers
    - service: script.sonos_set_group_volume
      data:
        volume: 0.2

################# GO TO BED #################

- alias: 'Go to bed weekdays'
  initial_state: on
  trigger:
    platform: time
    at: '22:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - sun
  action:
    service: scene.turn_on
    entity_id: scene.go_to_bed

- alias: 'Go to bed weekend'
  initial_state: on
  trigger:
    platform: time
    at: '23:59:00'
  condition:
    condition: time
    weekday:
      - fri
      - sat
  action:
    service: scene.turn_on
    entity_id: scene.go_to_bed

- alias: 'Turn off bedroom lights'
  initial_state: on
  trigger:
    platform: state
    entity_id: light.bedside_lamp_bedroom
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.sovrum

################# HUE SWITCH #################

- alias: 'Hue switch bright'
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.hallway_switch_updated
  condition:
    condition: state
    entity_id: sensor.hallway_switch
    state: '1_click_up'
  action:
    - service: scene.turn_on
      entity_id: scene.vardagsrum_bright
    - service: scene.turn_on
      entity_id: scene.hall_bright

- alias: 'Hue switch relaxed'
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.hallway_switch_updated
  condition:
    condition: state
    entity_id: sensor.hallway_switch
    state: '1_hold'
  action:
    - service: scene.turn_on
      entity_id: scene.vardagsrum_relaxed
    - service: scene.turn_on
      entity_id: scene.sovrum_relaxed
    - service: scene.turn_on
      entity_id: scene.hall_relaxed

- alias: 'Hue switch turn off lighs'
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.hallway_switch_updated
  condition:
    condition: state
    entity_id: sensor.hallway_switch
    state: '4_click_up'
  action:
    service: scene.turn_on
    entity_id: scene.all_lights_off

- alias: 'Hue switch group Sonos speakers'
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.hallway_switch_updated
  condition:
    condition: state
    entity_id: sensor.hallway_switch
    state: '2_hold'
  action:
    service: script.sonos_manual_group_speakers

- alias: 'Hue switch set Sonos group volume'
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.hallway_switch_updated
  condition:
    condition: state
    entity_id: sensor.hallway_switch
    state: '3_hold'
  action:
    service: script.sonos_set_group_volume
    data:
      volume: 0.05

- alias: 'Hue switch increase Sonos group volume'
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.hallway_switch_updated
  condition:
    condition: state
    entity_id: sensor.hallway_switch
    state: '2_click_up'
  action:
    service: script.sonos_increase_volume

- alias: 'Hue switch decrease Sonos group volume'
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.hallway_switch_updated
  condition:
    condition: state
    entity_id: sensor.hallway_switch
    state: '3_click_up'
  action:
    service: script.sonos_decrease_volume

################# LEAVING/COMING HOME #################

- alias: 'Leaving home'
  initial_state: on
  trigger:
    platform: state
    entity_id: group.device_tracker_family
    to: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.all_lights_off

- alias: 'Coming home'
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.device_tracker_family
      to: 'home'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: sun
        before: sunrise
        before_offset: '1:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.vardagsrum_bright
    - service: scene.turn_on
      entity_id: scene.sovrum_bright
    - service: scene.turn_on
      entity_id: scene.hall_bright

- alias: 'Car coming home'
  initial_state: on
  trigger:
    platform: state
    entity_id: device_tracker.volvo_lgd321
    to: 'home'
  condition:
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: '-01:00:00'
        - condition: sun
          before: sunrise
          before_offset: '1:00:00'
    - condition: state
      entity_id: group.device_tracker_family
      state: 'not_home'
  action:
    - service: scene.turn_on
      entity_id: scene.vardagsrum_bright
    - service: scene.turn_on
      entity_id: scene.sovrum_bright
    - service: scene.turn_on
      entity_id: scene.hall_bright

################# BATHROOM #################

- alias: 'Closing bathroom door'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_door
    to: 'off'
  condition:
    - condition: or
      conditions:
        - condition: time
          after: '22:30:00'
        - condition: time
          before: '07:00:00'
    - condition: state
      entity_id: group.device_tracker_family
      state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.bathroom_led_relaxed

- alias: 'Opening bathroom door'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_door
    to: 'on'
  action:
    service: light.turn_off
    entity_id: light.led_strip_2

################# MEDIA #################

- alias: 'Kodi playing'
  initial_state: on
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '20:30:00'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-01:00:00'
          - condition: sun
            before: sunrise
            before_offset: '1:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.watching_tv

- alias: 'TV off group speakers'
  initial_state: on
  trigger:
    platform: state
    entity_id: media_player.tv
    to: 'off'
  # condition:
  #   condition: state
  #   entity_id: binary_sensor.sonos_livingroom_playing_music
  #   state: 'off'
  action:
    - service: script.sonos_group_speakers
    - service: script.sonos_sync_group_volume

- alias: 'TV off disable night mode'
  initial_state: on
  trigger:
    platform: state
    entity_id: media_player.tv
    to: 'off'
  action:
    service: script.sonos_disable_night_mode

################# CAR HEATER #################

- alias: 'Car heater weekdays'
  initial_state: off
  trigger:
    platform: state
    entity_id: binary_sensor.car_heater_trigger_workdays
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.outside_temperature
        below: 3
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: group.device_tracker_family
        state: 'home'
      - condition: state
        entity_id: switch.lgd321_heater
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.lgd321_heater

- alias: 'Car heater audio notification'
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.lgd321_heater
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.davidsiphone
    state: 'home'
  action: 
    service: script.sonos_say
    data:
      sonos_entity: kok
      volume: 0.1
      message: 'Car heater turned on'
