- platform: workday
  country: SE
- platform: template
  sensors:
    sonos_night_mode:
      friendly_name: 'Status'
      icon_template: mdi:check-circle-outline
      value_template: '{{ states.media_player.vardagsrum.attributes.night_sound }}'
    alarm_clock_trigger_weekdays:
      friendly_name: 'Alarm clock trigger weekdays'
      value_template: >-
        {{ (as_timestamp(strptime(states.sensor.alarm_clock_time_weekdays.state, '%H:%M')) | int + 60*60 - 30*60) | timestamp_custom('%H:%M', false) == states.sensor.time.state }}
    alarm_clock_trigger_weekend:
      friendly_name: 'Alarm clock trigger weekend'
      value_template: >-
        {{ (as_timestamp(strptime(states.sensor.alarm_clock_time_weekend.state, '%H:%M')) | int + 60*60 - 30*60) | timestamp_custom('%H:%M', false) == states.sensor.time.state  }}
    car_heater_trigger_workdays:
      friendly_name: 'Car heater trigger workdays'
      value_template: >-
        {{ (as_timestamp(strptime(states.sensor.alarm_clock_time_weekdays.state, '%H:%M')) | int + 60*60 + states.input_number.alarm_heater_offset.state | int * 60) | timestamp_custom('%H:%M', false) == states.sensor.time.state }}
    sonos_livingroom_playing_music:
      friendly_name: 'Sonos livingroom playing music'
      value_template: >-
        {{ states.media_player.vardagsrum.attributes.media_artist != 'TV'}}
    sonos_livingroom_ungrouped:
      value_template: >-
        {{ states.media_player.vardagsrum.attributes.sonos_group == ['media_player.vardagsrum'] }}
    sonos_kitchen_grouped:
      value_template: >-
        {{ states.media_player.kok.attributes.sonos_group != ['media_player.kok']}}
    transmission_active:
      value_template: >-
        {{ states.sensor.transmission_status.state != 'idle' }}