- platform: workday
  name: 'Workday sensor'
  country: SE
  add_holidays:
    - '2020-05-22'
    - '2020-12-28'
    - '2020-12-29'
    - '2020-12-30'
- platform: workday
  name: 'Workday sensor offset'
  days_offset: 1
  country: SE
  add_holidays:
    - '2020-05-22'
    - '2020-12-28'
    - '2020-12-29'
    - '2020-12-30'

- platform: template
  sensors:
    sonos_night_mode:
      friendly_name: 'Status'
      icon_template: mdi:check-circle-outline
      value_template: >
        {{ state_attr('media_player.livingroom_sonos','night_sound') }}
    alarm_clock_trigger_weekdays:
      friendly_name: 'Alarm clock trigger weekdays'
      value_template: >
        {{ (as_timestamp(strptime(states('sensor.alarm_clock_time_weekdays'), '%H:%M')) | int + 60*60 - 30*60) | timestamp_custom('%H:%M', false) == states('sensor.time') }}
    alarm_clock_trigger_weekend:
      friendly_name: 'Alarm clock trigger weekend'
      value_template: >
        {{ (as_timestamp(strptime(states('sensor.alarm_clock_time_weekend'), '%H:%M')) | int + 60*60 - 30*60) | timestamp_custom('%H:%M', false) == states('sensor.time') }}
    car_heater_trigger_workdays:
      friendly_name: 'Car heater trigger workdays'
      value_template: >
        {{ (as_timestamp(strptime(states('sensor.alarm_clock_time_weekdays'), '%H:%M')) | int + 60*60 + states('input_number.alarm_heater_offset') | int * 60) | timestamp_custom('%H:%M', false) == states('sensor.time') }}
    relaxed_mode:
      value_template: >
        {{ ((as_timestamp(strptime(states('sensor.relaxed_mode_time'), '%H:%M')) | int) < (as_timestamp(strptime(states('sensor.time'), '%H:%M')) + 60) | int) or ((as_timestamp(strptime(states('sensor.time'), '%H:%M')) | int) < (as_timestamp(strptime('05:00', '%H:%M')) | int)) }}
    livingroom_sonos_tv_active:
      value_template: >
        {{ is_state_attr('media_player.livingroom_sonos','source','TV') }}
    kitchen_sonos_is_grouped:
      value_template: >
        {{ not is_state_attr('media_player.kitchen_sonos','group_members',['media_player.kitchen_sonos']) }}
    livingroom_sonos_is_grouped:
      value_template: >
        {{ not is_state_attr('media_player.livingroom_sonos','group_members',['media_player.livingroom_sonos']) }}
    childroom_sonos_is_grouped:
      value_template: >
        {{ not is_state_attr('media_player.childroom_sonos','group_members',['media_player.childroom_sonos']) }}
    transmission_active:
      value_template: >
        {{ not (is_state('sensor.transmission_status','idle') or is_state('sensor.transmission_status','unavailable')) }}
    bathroom_low_brightness_recently_executed:
      value_template: >
        {{ (utcnow() - states.script.bathroom_low_brightness.last_changed) < timedelta(seconds = 10) }}