- platform: template
  sensors:
    sonos_night_mode:
      friendly_name: 'Status'
      icon_template: mdi:check-circle-outline
      value_template: >
        {{ state_attr('media_player.livingroom_sonos','night_sound') }}
    relaxed_mode:
      value_template: >
        {{ states('sensor.time') > states('input_datetime.relaxed_mode') or now() < today_at("06:00") }}
    livingroom_sonos_tv_active:
      value_template: >
        {{ is_state_attr('media_player.livingroom_sonos','source','TV') }}
    kitchen_sonos_is_grouped:
      value_template: >
        {{ not is_state_attr('media_player.kitchen_sonos','group_members',['media_player.kitchen_sonos']) }}
    livingroom_sonos_is_grouped:
      value_template: >
        {{ not is_state_attr('media_player.livingroom_sonos','group_members',['media_player.livingroom_sonos']) }}
    girlroom_sonos_is_grouped:
      value_template: >
        {{ not is_state_attr('media_player.girlroom_sonos','group_members',['media_player.girlroom_sonos']) }}