- platform: group
  name: 'Hallway ceiling group 1'
  entities:
    - light.hallway_ceiling_1_1
    - light.hallway_ceiling_1_2
    - light.hallway_ceiling_1_3
- platform: group
  name: 'Hallway ceiling group 2'
  entities:
    - light.hallway_ceiling_2_1
    - light.hallway_ceiling_2_2
    - light.hallway_ceiling_2_3
- platform: group
  name: 'Hallway ceiling group'
  entities:
    - light.hallway_ceiling_1_1
    - light.hallway_ceiling_1_2
    - light.hallway_ceiling_1_3
    - light.hallway_ceiling_2_1
    - light.hallway_ceiling_2_2
    - light.hallway_ceiling_2_3
    - light.hallway_ceiling
- platform: group
  name: 'Bedroom bedside group'
  entities:
    - light.control_outlet_2
    - light.control_outlet_3
  