- platform: switch
  name: Livingroom window
  entity_id: switch.livingroom_shelly_1

- platform: group
  name: 'Hallway ceiling top floor'
  unique_id: hallway-ceiling-top-floor
  entities:
    - light.hallway_ceiling_1_1
    - light.hallway_ceiling_1_2
    - light.hallway_ceiling_1_3
- platform: group
  name: 'Hallway ceiling bottom floor'
  unique_id: hallway-ceiling-bottom-floor
  entities:
    - light.hallway_ceiling_2_1
    - light.hallway_ceiling_2_2
    - light.hallway_ceiling_2_3
- platform: group
  name: 'Hallway ceiling group'
  unique_id: hallway-ceiling
  entities:
    - light.hallway_ceiling_1_1
    - light.hallway_ceiling_1_2
    - light.hallway_ceiling_1_3
    - light.hallway_ceiling_2_1
    - light.hallway_ceiling_2_2
    - light.hallway_ceiling_2_3
- platform: group
  name: 'Hallway stair group'
  unique_id: 'hallway-stair'
  entities:
    - light.hallway_stair_down
    - light.hallway_stair_up
- platform: group
  name: 'Bedroom bedside'
  unique_id: bedroom-bedside
  entities:
    - light.bedroom_bedside_1
    - light.bedroom_bedside_2
- platform: group
  name: 'Outdoor porch'
  unique_id: outdoor-porch
  entities:
    - light.outdoor_porch_1
    - light.outdoor_porch_2
    - light.outdoor_porch_3
    - light.outdoor_porch_4