- platform: switch
  name: Livingroom window
  entity_id: switch.shelly_livingroom_1
- platform: switch
  name: Office window
  entity_id: switch.control_outlet_2
- platform: switch
  name: Bedroom bedside 1
  entity_id: switch.control_outlet_3
- platform: switch
  name: Bedroom bedside 2
  entity_id: switch.control_outlet_4

- platform: group
  name: 'Hallway ceiling top floor'
  entities:
    - light.hallway_ceiling_1_1
    - light.hallway_ceiling_1_2
    - light.hallway_ceiling_1_3
- platform: group
  name: 'Hallway ceiling bottom floor'
  entities:
    - light.hallway_ceiling_2_1
    - light.hallway_ceiling_2_2
    - light.hallway_ceiling_2_3
- platform: group
  name: 'Hallway ceiling group'
  entities:
    - light.hallway_ceiling_1_1
    - light.hallway_ceiling_1_2
    - light.hallway_ceiling_1_3
    - light.hallway_ceiling_2_1
    - light.hallway_ceiling_2_2
    - light.hallway_ceiling_2_3
    - light.hallway_ceiling
- platform: group
  name: 'Bedroom bedside'
  entities:
    - light.bedroom_bedside_1
    - light.bedroom_bedside_2