- platform: template
  lights:
    bedroom_bedside_1:
      friendly_name: 'Sänglampa 1 sovrum'
      icon_template: mdi:lamp
      value_template: '{{ states.switch.bedside_lamp_bedroom.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.bedside_lamp_bedroom
      turn_off:
        service: switch.turn_off
        entity_id: switch.bedside_lamp_bedroom
    bedroom_bedside_2:
      friendly_name: 'Sänglampa 2 sovrum'
      icon_template: mdi:lamp
      value_template: '{{ states.switch.bedside_lamp_bedroom_2.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.bedside_lamp_bedroom_2
      turn_off:
        service: switch.turn_off
        entity_id: switch.bedside_lamp_bedroom_2

- platform: group
  name: 'Hallway ceiling group 1'
  entities:
    - light.hallway_ceiling_1_1
    - light.hallway_ceiling_1_2
    - light.hallway_ceiling_1_3
- platform: group
  name: 'Hallway ceiling group 2'
  entities:
    - light.hallway_ceiling_2_1
    - light.hallway_ceiling_2_2
    - light.hallway_ceiling_2_3
- platform: group
  name: 'Hallway ceiling group'
  entities:
    - light.hallway_ceiling_1_1
    - light.hallway_ceiling_1_2
    - light.hallway_ceiling_1_3
    - light.hallway_ceiling_2_1
    - light.hallway_ceiling_2_2
    - light.hallway_ceiling_2_3
    - light.hallway_ceiling
- platform: group
  name: 'Bedroom bedside group'
  entities:
    - light.bedroom_bedside_1
    - light.bedroom_bedside_2
  