- platform: yr
  monitored_conditions:
    - symbol
    - temperature

- platform: plex_recently_added
  host: !secret oden_ip
  port: 32400
  token: !secret plex_token
  ssl: true
  ssl_cert: false
  download_images: true
  max: 5
  section_types:
    - movie
    - show

- platform: trakt
  id: !secret trakt_id
  secret: !secret trakt_secret
  username: !secret trakt_username
  days: 10

- platform: krisinformation
  name: "Krisinformation Skåne"
  county: "Skåne län"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 100

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - !secret steam_id_klench
    - !secret steam_id_mench
    - !secret steam_id_bench
    - !secret steam_id_lady_nelson
    - !secret steam_id_olrik_meister
    - !secret steam_id_tdq

- platform: apcupsd
  resources:
    - status
    - date
    - starttime
    - linev
    - loadpct
    - bcharge
    - timeleft
    - mbattchg
    - mintimel

- platform: template
  sensors:
    alarm_clock_time_weekdays:
      friendly_name: 'Väckningstid'
      icon_template: mdi:alarm
      value_template: '{{ "%0.02d:%0.02d" | format(states.input_number.alarm_hours_weekdays.state | int, states.input_number.alarm_minutes_weekdays.state | int ) }}'
    alarm_clock_time_weekend:
      friendly_name: 'Väckningstid'
      icon_template: mdi:alarm
      value_template: '{{ "%0.02d:%0.02d" | format(states.input_number.alarm_hours_weekend.state | int, states.input_number.alarm_minutes_weekend.state | int ) }}'
    relaxed_mode_time:
      friendly_name: 'Klockslag'
      icon_template: mdi:alarm
      value_template: '{{ "%0.02d:%0.02d" | format(states.input_number.relaxed_mode_hours.state | int, states.input_number.relaxed_mode_minutes.state | int ) }}'
    outdoor_temperature:
      friendly_name: 'Temperatur'
      icon_template: mdi:thermometer
      unit_of_measurement: '°C'
      value_template: '{{ (float(states.sensor.yr_temperature.state) * 0.4 + float(states.weather.smhi_hem.attributes.temperature) * 0.6) | round(1) }}'
    hallway_switch_updated:
      friendly_name: 'Hallway switch updated'
      value_template: '{{ states.remote.hallway_switch.attributes.last_updated }}'
    work_time_in:
      friendly_name: 'Inpasseringstid'
      icon_template: mdi:clock-in
      value_template: '{{ "%0.02d:%0.02d" | format(states.input_number.work_time_hours_in.state | int, states.input_number.work_time_minutes_in.state | int ) }}'
    work_time_out:
      friendly_name: 'Utpasseringstid'
      icon_template: mdi:clock-out
      value_template: '{{ "%0.02d:%0.02d" | format(states.input_number.work_time_hours_out.state | int, states.input_number.work_time_minutes_out.state | int ) }}'
    work_time:
      friendly_name: 'Arbetstid timmar'
      icon_template: mdi:calendar-clock
      value_template: >-
        {{ float((as_timestamp(strptime(states.sensor.work_time_out.state, '%H:%M')) | int - as_timestamp(strptime(states.sensor.work_time_in.state, '%H:%M')) | int - states.input_number.work_time_minutes_lunch.state | int * 60)/3600) | round(1) }}
    bedroom_music_timer_duration:
      value_template: '{{ "00:%0.02d:00" | format(states.input_number.bedroom_music_timer_minutes.state | int) }}'
    bedroom_music_timer_minutes:
      friendly_name: 'Längd'
      icon_template: mdi:timer
      unit_of_measurement: 'min'
      value_template: '{{ states.input_number.bedroom_music_timer_minutes.state | round(0) }}'