- platform: krisinformation
  name: "Krisinformation Skåne"
  county: "Skåne län"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 100

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: apcupsd
  resources:
    - status
    - date
    - starttime
    - linev
    - loadpct
    - bcharge
    - timeleft
    - mbattchg
    - mintimel

- platform: qbittorrent
  url: !secret qbittorrent_url
  username: !secret qbittorrent_username
  password: !secret qbittorrent_password

- platform: skolmaten
  sensors:
    - school: junibackens-forskola7

- platform: rest
  resource: https://henrikhjelm.se/api/getdata.php?lan=skane-lan
  name: OKQ8
  value_template: '{{ value_json.skanelan_OKQ8_AngelholmOstra_vagen_17__diesel | float }}'
  unit_of_measurement: 'kr'
  scan_interval: 1800
- platform: rest
  resource: https://henrikhjelm.se/api/getdata.php?lan=skane-lan
  name: ST1
  value_template: '{{ value_json.skanelan_St1_AngelholmHelsingborgsvagen_49__diesel | float }}'
  unit_of_measurement: 'kr'
  scan_interval: 1800
- platform: rest
  resource: https://henrikhjelm.se/api/getdata.php?lan=skane-lan
  name: Tanka
  value_template: '{{ value_json.skanelan_Tanka_AngelholmTransportgatan_11__diesel | float }}'
  unit_of_measurement: 'kr'
  scan_interval: 1800

- platform: template
  sensors:
    alarm_clock_time_weekdays:
      friendly_name: 'Väckningstid'
      icon_template: mdi:alarm
      value_template: >
        {{ "%0.02d:%0.02d" | format(states('input_number.alarm_hours_weekdays') | int, states('input_number.alarm_minutes_weekdays') | int ) }}
    alarm_clock_time_weekend:
      friendly_name: 'Väckningstid'
      icon_template: mdi:alarm
      value_template: >
        {{ "%0.02d:%0.02d" | format(states('input_number.alarm_hours_weekend') | int, states('input_number.alarm_minutes_weekend') | int ) }}
    outdoor_temperature:
      friendly_name: 'Temperatur'
      icon_template: mdi:thermometer
      unit_of_measurement: '°C'
      value_template: >
        {{ (state_attr('weather.met_hem','temperature') * 0.4 + state_attr('weather.smhi_hem','temperature') * 0.6) | round(1) }}
    hallway_switch_updated:
      friendly_name: 'Hallway switch updated'
      value_template: >
        {{ state_attr('remote.hallway_switch','last_updated') }}
    work_time_in:
      friendly_name: 'Inpasseringstid'
      icon_template: mdi:clock-in
      value_template: >
        {{ "%0.02d:%0.02d" | format(states('input_number.work_time_hours_in') | int, states('input_number.work_time_minutes_in') | int ) }}
    work_time_out:
      friendly_name: 'Utpasseringstid'
      icon_template: mdi:clock-out
      value_template: >
        {{ "%0.02d:%0.02d" | format(states('input_number.work_time_hours_out') | int, states('input_number.work_time_minutes_out') | int ) }}
    work_time:
      friendly_name: 'Arbetstid timmar'
      icon_template: mdi:calendar-clock
      value_template: >
        {{ float((as_timestamp(strptime(states('sensor.work_time_out'), '%H:%M')) | int - as_timestamp(strptime(states('sensor.work_time_in'), '%H:%M')) | int - states('input_number.work_time_minutes_lunch') | int * 60)/3600) | round(1) }}
    bedroom_music_timer_duration:
      value_template: >
        {{ "00:%0.02d:00" | format(states('input_number.bedroom_music_timer_minutes') | int) }}
    bedroom_music_timer_minutes:
      friendly_name: 'Längd'
      icon_template: mdi:timer-outline
      unit_of_measurement: 'min'
      value_template: >
        {{ states('input_number.bedroom_music_timer_minutes') | round(0) }}
    vacuum_mode_neato:
      value_template: >
        {% if is_state('input_boolean.vacuum_eco_mode','on') %}
          {{ 1 }}
        {% else %}
          {{ 2 }}
        {% endif %}
    vacuum_extra_care_neato:
      value_template: >
        {% if is_state('input_boolean.vacuum_extra_care','on') %}
          {{ 2 }}
        {% else %}
          {{ 1 }}
        {% endif %}
    ups_power_delivery:
      friendly_name: UPS Power Delivery
      icon_template: mdi:flash
      unit_of_measurement: W
      value_template: >
        {{ ((states('sensor.ups_load') | int) * 0.01 * 330) | int }}
    car_status:
      friendly_name: Bilen
      icon_template: mdi:car
      value_template: >
        {% if is_state('binary_sensor.rcb492_engine','on') %}
          Aktiv
        {% elif not is_state('binary_sensor.rcb492_engine','on') and is_state('device_tracker.rcb492','not_home') %}
          Borta
        {% else %}
          {{ states('device_tracker.rcb492') }}
        {% endif %}