- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: skolmat
  name: "Södra Utmarkens skola"
  url: "https://skolmaten.se/sodra-utmarkens-skola"
  unique_id: "skolmaten"