- platform: template
  switches:
    sonos_night_mode:
      friendly_name: 'Nattläge'
      icon_template: mdi:sleep
      value_template: >
        {{ state_attr('media_player.livingroom_sonos','night_sound') }}
      turn_on:
        service: script.sonos_enable_night_mode
      turn_off:
        service: script.sonos_disable_night_mode

- platform: wake_on_lan
  name: WOL Vidar
  mac: !secret vidar_mac
  host: !secret vidar_ip
- platform: wake_on_lan
  name: WOL RPI 3B
  mac: !secret rpi3b_mac
  host: !secret rpi3b_ip