- platform: wake_on_lan
  name: WOL Oden
  mac: !secret oden_mac
  host: !secret oden_ip
- platform: wake_on_lan
  name: WOL Vidar
  mac: !secret vidar_mac
  host: !secret vidar_ip
- platform: wake_on_lan
  name: WOL RPI 3B
  mac: !secret rpi3b_mac
  host: !secret rpi3b_ip