title: Stenman

views:

################# HOME #################

  - icon: mdi:home-assistant
    cards:

      - type: glance
        # state_color: false
        entities:
          - device_tracker.davids_iphone
          - device_tracker.nellies_iphone
          - device_tracker.volvo_lgd321
          - entity: sensor.lgd321_range
            name: 'Räckvidd'
          - entity: switch.lgd321_heater
            name: 'Värmare'
          - sensor.outdoor_temperature
          - entity: sensor.plex_oden
            name: Plex
            icon: mdi:plex
          - entity: sensor.hacs
            name: 'HACS'
          - entity: sensor.potential_breaking_changes
            name: 'Ändringar'
            icon: mdi:briefcase-download-outline
          - entity: sensor.ups_status
            name: 'UPS'
            icon: mdi:power-plug-outline

      - type: entities
        title: Belysning
        show_header_toggle: false
        entities:
          - entity: script.all_rooms_bright
            icon: mdi:lightbulb-on-outline
          - entity: script.all_rooms_relaxed
            icon: mdi:lightbulb-on
          - entity: script.all_lights_off
            icon: mdi:lightbulb-off

      - type: entities
        title: Vardagsrum
        show_header_toggle: false
        entities:
          - entity: script.livingroom_bright
            icon: mdi:lightbulb-on-outline
          - entity: script.livingroom_relaxed
            icon: mdi:lightbulb-on
          - light.hue_ambiance_lamp_1
          - light.hue_ambiance_lamp_1_3
          - light.window_lamp_livingroom

      - type: entities
        title: Hall
        show_header_toggle: false
        entities:
          - entity: script.hallway_bright
            icon: mdi:lightbulb-on-outline
          - entity: script.hallway_low_brightness
            icon: mdi:lightbulb-on
          - entity: script.hallway_relaxed
            icon: mdi:lightbulb-on
          - entity: light.ceiling_lamps_hallway
            icon: mdi:ceiling-light
            name: 'Taklampor hall'

      - type: entities
        title: Sovrum
        show_header_toggle: false
        entities:
          - entity: script.bedroom_bright
            icon: mdi:lightbulb-on-outline
          - entity: script.bedroom_relaxed
            icon: mdi:lightbulb-on
          - light.hue_ambiance_lamp_2
          - entity: light.bedside_lamps_bedroom
            icon: mdi:lamp
            name: 'Sänglampor'

      - type: entities
        title: Kök
        show_header_toggle: false
        entities:
          - entity: script.kitchen_bright
            icon: mdi:lightbulb-on-outline
          - entity: script.kitchen_relaxed
            icon: mdi:lightbulb-on
          - light.table_lamp_kitchen
          - entity: light.ceiling_lamp_hallway
            name: 'Taklampa kök'

      - type: conditional
        conditions:
          - entity: media_player.apple_tv_vardagsrum
            state_not: 'idle'
        card:
          type: custom:mini-media-player
          entity: media_player.apple_tv_vardagsrum
          replace_mute: stop
          hide:
            volume: true
            power: true
          idle_view:
            when_idle: true
            when_standby: true
          artwork: full-cover
          icon: mdi:television-classic

      - type: conditional
        conditions:
          - entity: media_player.spotify
            state: 'playing'
        card:
          type: custom:mini-media-player
          entity: media_player.spotify
          artwork: cover
          icon: mdi:spotify
          name: Spotify
          hide:
            power: true
            volume: true
          idle_view:
            when_idle: true
            when_paused: true
            when_standby: true

      - type: custom:mini-graph-card
        entities:
          - sensor.outdoor_temperature
        name: 'Yttertemperatur'
        unit: '°C'
        line_color: '#5c8dd1'
        hour24: true
        animate: true
        decimals: 1
        points_per_hour: 1
        font_size_header: 18
        show:
          extrema: true
          labels: true
          fill: fade

      - type: weather-forecast
        entity: weather.smhi_hem
        
      - type: custom:krisinfo-card
        entity: sensor.krisinformation_skane

      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Gästnätverk
          show_header_toggle: false
        filter:
          include:
            - domain: device_tracker
              state: home
              attributes:
                essid: "Stenman_guest"

      - type: entities
        title: Steam
        entities:
        - type: custom:multiple-entity-row
          entity: sensor.steam_76561198017790086
          secondary_info:
            attribute: game
        - type: custom:multiple-entity-row
          entity: sensor.steam_76561198105180724
          secondary_info:
            attribute: game
        - type: custom:multiple-entity-row
          entity: sensor.steam_76561198002571233
          secondary_info:
            attribute: game
        - type: custom:multiple-entity-row
          entity: sensor.steam_76561198024634860
          secondary_info:
            attribute: game
        - type: custom:multiple-entity-row
          entity: sensor.steam_76561198129920804
          secondary_info:
            attribute: game

################# SONOS #################

  - icon: mdi:speaker-wireless
    cards:

      - type: custom:mini-media-player
        entity: media_player.sonos_kitchen
        hide:
          power: true
          source: true
        artwork: full-cover
        icon: mdi:speaker-multiple
        speaker_group:
          platform: sonos
          sync_volume: true
          expanded: true
          show_group_count: true
          entities:
            - entity_id: media_player.sonos_livingroom
              name: Sonos vardagsrum
            - entity_id: media_player.sonos_bedroom
              name: Sonos sovrum
#        tts:
#          platform: sonos
#          language: english
#          entity_id:
#            - media_player.sonos_kitchen
#            - media_player.sonos_bedroom
#            - media_player.sonos_livingroom
#          volume: 0.3

      - type: custom:mini-media-player
        entity: media_player.sonos_bedroom
        artwork: cover
        icon: mdi:speaker
        hide:
          power: true
          source: true
        speaker_group:
          platform: sonos
          show_group_count: false

      - type: custom:mini-media-player
        entity: media_player.sonos_livingroom
        artwork: cover
        icon: mdi:speaker
        hide:
          power: true
          source: true
        speaker_group:
          platform: sonos
          show_group_count: false

      - type: conditional
        conditions:
          - entity: binary_sensor.sonos_kitchen_is_grouped
            state: 'on'
        card:
          type: custom:mini-media-player
          entity: media_player.sonos_kitchen
          artwork: cover
          icon: mdi:speaker
          hide:
            power: true
            source: true
          speaker_group:
            platform: sonos
            show_group_count: false

      - type: entities
        title: Nattläge Sonos Beam
        show_header_toggle: false
        entities:
          - entity: switch.sonos_night_mode
            state_color: true

      - type: conditional
        conditions:
          - entity: media_player.sonos_bedroom
            state: 'playing'
          - entity: binary_sensor.sonos_bedroom_is_grouped
            state: 'off'
        card:
          type: vertical-stack
          title: Timer sovrum
          cards:
            - type: horizontal-stack
              cards:
                - type: button
                  name: 'Start'
                  icon: mdi:play
                  tap_action:
                    action: call-service
                    service: script.bedroom_music_timer_start
                - type: button
                  name: 'Stopp'
                  icon: mdi:stop
                  tap_action:
                    action: call-service
                    service: script.bedroom_music_timer_cancel
                - type: entity
                  entity: sensor.bedroom_music_timer_minutes
            - type: entities
              entities:
                - entity: timer.bedroom_music_timer
                  name: 'Status'
                  icon: mdi:timelapse
                - input_number.bedroom_music_timer_minutes

      - type: conditional
        conditions:
          - entity: binary_sensor.sonos_livingroom_tv_active
            state: 'on'
        card:
          type: custom:mini-media-player
          entity: media_player.sonos_livingroom
          hide:
            power: true
            source: true
          artwork: cover
          icon: mdi:television-classic
          speaker_group:
            platform: sonos
            sync_volume: false
            expanded: true
            show_group_count: true
            entities:
              - entity_id: media_player.sonos_kitchen
                name: Sonos kök
              - entity_id: media_player.sonos_bedroom
                name: Sonos sovrum

  - icon: mdi:server-network
    cards:

      # - type: custom:auto-entities
      #   card:
      #     type: entities
      #     title: Unraid
      #     show_header_toggle: false
      #   filter:
      #     include:
      #       - entity_id: "sensor.unraid*"

      - type: entities
        title: Unraid
        show_header_toggle: false
        entities:
          - entity: sensor.unraid_mnt_disk1_used_percent
            name: 'Diskanvändning disk 1'
          - entity: sensor.unraid_mnt_disk2_used_percent
            name: 'Diskanvändning disk 2'
          - entity: sensor.unraid_mnt_disk3_used_percent
            name: 'Diskanvändning disk 3'
          - entity: sensor.unraid_cpu_used
            name: 'Processoranvändning'
          - entity: sensor.unraid_ram_used_percent
            name: 'Ramanvändning'
          - entity: sensor.unraid_ram_used
            name: 'Ramanvändning'
          - entity: sensor.unraid_containers_active
            name: 'Aktiva docker containers'
          - entity: sensor.unraid_containers_cpu_used
            name: 'Processoranvänding docker containers'
          - entity: sensor.unraid_containers_ram_used
            name: 'Ramanvändning docker containers'
          - entity: sensor.unraid_cputin_temp
            name: 'Temperatur CPU'
          - entity: sensor.unraid_auxtin0_temp
            name: 'Temperatur moderkort'

      - type: custom:auto-entities
        card:
          type: entities
          title: Unraid UPS
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.ups*"

################# WAKEUP #################

  - icon: mdi:alarm
    cards:
     
      - type: entities
        title: Väckning vardagar
        show_header_toggle: false
        entities:
          - sensor.alarm_clock_time_weekdays
          - input_number.alarm_hours_weekdays
          - input_number.alarm_minutes_weekdays
          - input_number.alarm_heater_offset
          - entity: automation.wakeup_weekdays
            name: 'Väckning vardagar'
          - entity: automation.enable_sonos_alarm
            name: 'Sonos alarm'
          - input_boolean.wakeup_override
          - entity: automation.car_heater_weekdays
            name: 'Bränslevärmare'

      - type: entities
        title: Väckning helg
        show_header_toggle: false
        entities:
          - sensor.alarm_clock_time_weekend
          - input_number.alarm_hours_weekend
          - input_number.alarm_minutes_weekend
          - entity: automation.wakeup_weekend
            name: 'Väckning helg'

################# TV #################

  - icon: mdi:television-classic
    cards:

      - type: custom:upcoming-media-card
        entity: sensor.plex_recently_added
        title: Plex senast tillagt
        clock: 24
        image_style: fanart

      - type: custom:auto-entities
        show_empty: false
        card:
          # type: custom:mini-media-player
          # hide:
          #   power: true
          #   source: true
          #   volume: false
          # show_progress: true
          # artwork: full-cover
          # icon: mdi:plex
          type: entities
          title: Plex klienter
          show_header_toggle: false
        filter:
          include:
            - domain: media_player
              # name: /plex/
          exclude:
            - state: "inactive"
            - state: "unavailable"
            - state: "idle"

      - type: custom:upcoming-media-card
        entity: sensor.trakt_upcoming_calendar
        title: Kommande TV-serier
        clock: 24
        image_style: fanart
        hide_empty: true

################# CAR #################

  - icon: mdi:car
    cards:
      
      - type: entities
        title: Översikt
        show_header_toggle: false
        entities:
          - binary_sensor.lgd321_doors
          - binary_sensor.lgd321_windows
          - binary_sensor.lgd321_hood
          - binary_sensor.lgd321_brake_fluid
          - binary_sensor.lgd321_bulbs
          - binary_sensor.lgd321_service
          - binary_sensor.lgd321_washer_fluid
          - sensor.lgd321_fuel_level
          - sensor.lgd321_fuel_amount
          - sensor.lgd321_range
          - sensor.lgd321_fuel_consumption
          - switch.lgd321_heater

      - type: entities
        title: Detaljer
        show_header_toggle: false
        entities:
          - sensor.lgd321_last_trip
          - sensor.lgd321_odometer
          - sensor.lgd321_trip_meter_1
          - sensor.lgd321_trip_meter_2
          - binary_sensor.lgd321_front_left_door
          - binary_sensor.lgd321_front_right_door
          - binary_sensor.lgd321_rear_left_door
          - binary_sensor.lgd321_rear_right_door
          - binary_sensor.lgd321_front_left_window
          - binary_sensor.lgd321_front_right_window
          - binary_sensor.lgd321_rear_left_window
          - binary_sensor.lgd321_rear_right_window
          - binary_sensor.lgd321_front_left_tyre
          - binary_sensor.lgd321_front_right_tyre
          - binary_sensor.lgd321_rear_left_tyre
          - binary_sensor.lgd321_rear_right_tyre

################# WORK TIME #################

  - icon: mdi:briefcase-clock-outline
    cards:

      - type: entities
        title: Arbetstid
        show_header_toggle: false
        entities:
          - sensor.work_time
          - sensor.work_time_in
          - input_number.work_time_hours_in
          - input_number.work_time_minutes_in
          - sensor.work_time_out
          - input_number.work_time_hours_out
          - input_number.work_time_minutes_out
          - input_number.work_time_minutes_lunch

################# TRANSMISSION #################

  - icon: mdi:download-network-outline
    cards:

      - type: entities
        title: Transmission
        show_header_toggle: false
        entities:
          - input_text.transmission_torrent_url
          - entity: sensor.transmission_active_torrents
            name: Aktiva torrents
            icon: mdi:play
          - entity: sensor.transmission_paused_torrents
            name: Pausade torrents
            icon: mdi:pause
          - entity: sensor.transmission_completed_torrents
            name: Slutförda torrents
            icon: mdi:check
          - entity: switch.transmission_turtle_mode
            name: Turtle mode
            icon: mdi:tortoise

      - type: conditional
        conditions:
          - entity: binary_sensor.transmission_active
            state: 'on'
        card:
          type: horizontal-stack
          cards:
            - type: custom:mini-graph-card
              entities:
                - entity: sensor.transmission_down_speed
              name: 'Nedladdning'
              unit: 'MB/s'
              icon: mdi:file-download-outline
              line_color: '#5c8dd1'
              hour24: true
              hours_to_show: 2
              animate: true
              decimals: 2
              points_per_hour: 60
              font_size_header: 18
              show:
                extrema: true
                labels: true
                fill: fade
            - type: custom:mini-graph-card
              entities:
                - entity: sensor.transmission_up_speed
              name: 'Uppladdning'
              unit: 'MB/s'
              icon: mdi:file-upload-outline
              line_color: '#5c8dd1'
              hour24: true
              hours_to_show: 2
              animate: true
              decimals: 2
              points_per_hour: 60
              font_size_header: 18
              show:
                extrema: true
                labels: true
                fill: fade

################# AUTOMATIONS #################

  - icon: mdi:robot-industrial
    cards:

      - type: entities
        title: Tid för mysbelysning
        show_header_toggle: false
        entities:
          - sensor.relaxed_mode_time
          - input_number.relaxed_mode_hours
          - input_number.relaxed_mode_minutes

      - type: entities
        title: Automationer
        show_header_toggle: false
        entities:
          - automation.wakeup_weekdays
          - automation.enable_sonos_alarm
          - automation.wakeup_weekend
          - automation.go_to_bed_weekdays
          - automation.go_to_bed_weekend
          - automation.evening_bright
          - automation.evening_relaxed
          - automation.hallway_bright
          - automation.sunset
          - automation.bright_after_sunset
          - automation.turn_off_bedroom_lights
          - automation.closing_bathroom_door
          - automation.opening_bathroom_door
          - input_boolean.coming_home_turn_on_lights
          - automation.leaving_home
          - automation.watching_tv
          - automation.tv_off_group_speakers
          - automation.car_heater_weekdays

################# ESPHome #################

  - icon: mdi:developer-board
    cards:

      - type: entities
        title: Badrum
        show_header_toggle: false
        entities:
          - entity: binary_sensor.bathroom_door
            name: 'Badrumsdörr'
          - entity: light.bathroom_led
            name: LED-belysning
          - automation.closing_bathroom_door
          - automation.opening_bathroom_door