################# MEDIA #################

- alias: 'Watching TV'
  triggers:
    trigger: state
    entity_id: media_player.plex_vardagsrum
    to: 'playing'
  conditions:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: time
            after: '20:30:00'
          - condition: time
            before: '10:00:00'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-01:00:00'
          - condition: sun
            before: sunrise
            before_offset: '1:00:00'
  actions:
    action: script.watching_tv_lights

- alias: 'Decrease child room music volume when turning indoor lights off'
  initial_state: true
  triggers:
    trigger: state
    entity_id: script.indoor_lights_off
    to: 'on'
  conditions:
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
    - condition: state
      entity_id: media_player.childroom_sonos
      state: 'playing'
    - condition: state
      entity_id: binary_sensor.childroom_sonos_is_grouped
      state: 'off'
    - condition: template
      value_template: >
        {{ state_attr('media_player.childroom_sonos','volume_level') > 0.03 }}
  actions:
    action: python_script.media_player_volume_set
    data:
      entity_id: media_player.childroom_sonos
      volume_level: 0.03