################# TIME #################

- alias: 'Evening bright'
  triggers:
    trigger: sun
    event: sunset
    offset: '-01:00:00'
  conditions:
    - condition: state
      entity_id: group.device_tracker_family
      state: 'home'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
    - condition: time
      before: '19:00:00'
  actions:
    action: script.bottom_floor_bright

- alias: 'Evening relaxed'
  triggers:
    trigger: state
    entity_id: binary_sensor.relaxed_mode
    to: 'on'
  conditions:
    condition: state
    entity_id: group.device_tracker_family
    state: 'home'
  actions:
    - action: script.indoor_lights_relaxed
    - condition: state
      entity_id: binary_sensor.girlroom_sonos_is_grouped
      state: 'on'
    - action: script.sonos_ungroup_girlroom_speaker
    - condition: template
      value_template: >
        {{ state_attr('media_player.girlroom_sonos','volume_level') > 0.10 }}
    - action: media_player.volume_set
      data:
        entity_id: media_player.girlroom_sonos
        volume_level: 0.10

- alias: 'Hallway bright'
  triggers:
    trigger: time
    at: '09:00:00'
  conditions:
    condition: state
    entity_id: group.device_tracker_family
    state: 'home'
  actions:
    action: script.hallway_bright

################# SUNSET/SUNRISE #################

- alias: 'Sunset'
  triggers:
    trigger: sun
    event: sunset
  conditions:
    - condition: state
      entity_id: group.device_tracker_family
      state: 'home'
    - condition: state
      entity_id: group.indoor_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
  actions:
    action: script.turn_on
    target:
      entity_id: script.window_lights

- alias: 'Bright after sunset bedroom'
  initial_state: false
  triggers:
    trigger: state
    entity_id: script.bedroom_bright
    to: 'on'
  conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: input_boolean.window_lights_after_sunset
      state: 'on'
  actions:
    action: light.turn_on
    data:
      entity_id: light.bedroom_bedside
      brightness_pct: 100

- alias: 'Bright after sunset livingroom'
  initial_state: true
  triggers:
    trigger: state
    entity_id: script.livingroom_bright
    to: 'on'
  conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: input_boolean.window_lights_after_sunset
      state: 'on'
  actions:
    action: light.turn_on
    target:
      entity_id:
        - light.livingroom_window
        - light.bedroom_window

- alias: 'Outdoor lights at sunset'
  initial_state: true
  triggers:
    trigger: sun
    event: sunset
    offset: "00:05:00"
  actions:
    action: script.turn_on_outdoor_lights

- alias: 'Outdoor lights at sunrise'
  initial_state: true
  triggers:
    trigger: sun
    event: sunrise
  actions:
    action: script.turn_off_outdoor_lights

- alias: 'Outdoor lights when sun above horizon'
  initial_state: true
  triggers:
    trigger: time_pattern
    minutes: "/30"
  conditions:
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"
    - condition: state
      entity_id:
        - light.outdoor_main_entrance
        - light.outdoor_porch
      match: any
      state: 'on'
  actions:
    - action: script.turn_off_outdoor_lights

- alias: 'Turn off boy room night light at sunrise'
  initial_state: true
  triggers:
    trigger: sun
    event: sunrise
    offset: '02:00:00'
  actions:
    action: light.turn_off
    target:
      entity_id: light.boyroom_led_strip

################# WAKEUP #################

- alias: 'Wakeup weekdays'
  triggers:
    trigger: time
    at: input_datetime.wakeup_weekdays
  conditions:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.wakeup_override
        state: 'on'
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
          - condition: state
            entity_id: group.device_tracker_family
            state: 'home'
  actions:
    action: script.wakeup_lights

- alias: 'Wakeup weekend'
  triggers:
    trigger: time
    at: input_datetime.wakeup_weekend
  conditions:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: group.device_tracker_family
      state: 'home'
  actions:
    action: script.wakeup_lights

- alias: 'Boy room morning wakeup light workday'
  triggers:
    trigger: time
    at: '06:30:00'
  conditions:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  actions:
    action: light.turn_on
    data:
      entity_id: light.boyroom_led_strip
      brightness_pct: 12
      rgb_color: [0,0,255]
      transition: 2
      effect: None

- alias: 'Boy room morning wakeup light weekend'
  triggers:
    trigger: time
    at: '07:15:00'
  conditions:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  actions:
    action: light.turn_on
    data:
      entity_id: light.boyroom_led_strip
      brightness_pct: 12
      rgb_color: [0,0,255]
      transition: 2
      effect: None

################# AWAY #################

- alias: 'Away turn on lights'
  initial_state: true
  triggers:
    trigger: sun
    event: sunset
  conditions:
    - condition: state
      entity_id: input_boolean.enable_away_lights
      state: 'on'
    - condition: state
      entity_id: group.device_tracker_family
      state: 'not_home'
  actions:
    - action: script.enable_away_lights
    - action: input_boolean.turn_on
      data:
        entity_id: input_boolean.away_lights_active

- alias: 'Leaving home turn on lights'
  initial_state: true
  triggers:
    trigger: state
    entity_id: group.device_tracker_family
    to: 'not_home'
  conditions:
    - condition: state
      entity_id: input_boolean.enable_away_lights
      state: 'on'
    - condition: sun
      after: sunset
  actions:
    - action: script.enable_away_lights
    - action: input_boolean.turn_on
      data:
        entity_id: input_boolean.away_lights_active

- alias: 'Away turn off lights'
  initial_state: true
  triggers:
    trigger: time
    at: '23:30:00'
  conditions:
    - condition: state
      entity_id: group.device_tracker_family
      state: 'not_home'
    - condition: state
      entity_id: group.indoor_lights
      state: 'on'
  actions:
    - action: script.indoor_lights_off
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.away_lights_active

################# BATHROOM #################

- alias: 'Increase bathroom ceiling light brightness'
  initial_state: true
  triggers:
    trigger: state
    entity_id: light.bathroom_ceiling
    to: 'on'
  conditions:
    - condition: template
      value_template: >
        {{ state_attr('light.bathroom_ceiling','brightness') < 255 }}
    - condition: time
      after: '07:00:00'
      before: '18:00:00'
  actions:
    action: light.turn_on
    data:
      entity_id: light.bathroom_ceiling
      brightness_pct: 100

################# MOTION SENSOR #################

- alias: 'Hallway top floor motion hallway bright'
  initial_state: true
  triggers:
    trigger: state
    entity_id: binary_sensor.hallway_top_floor_motion
    to: 'on'
  conditions:
    - condition: state
      entity_id: input_boolean.enable_hue_motion_sensor_hallway
      state: 'on'
    - condition: state
      entity_id: light.hallway_ceiling_top_floor
      state: 'off'
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: 'off'
            - condition: time
              before: '18:00:00'
              after: '09:30:00'
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: 'on'
            - condition: time
              before: '18:00:00'
              after: '07:00:00'
    - condition: template
      value_template: >
        {{ is_state_attr('light.hallway_ceiling_bottom_floor','brightness',255) }}
    - condition: template
      value_template: >
        {{ not (is_state('binary_sensor.girlroom_sonos_is_grouped','off') and is_state('media_player.girlroom_sonos','playing')) }}
  actions:
    action: script.hallway_top_floor_bright

- alias: 'Hallway top floor motion rooms bright'
  initial_state: true
  triggers:
    trigger: state
    entity_id: binary_sensor.hallway_top_floor_motion
    to: 'on'
  conditions:
    - condition: state
      entity_id: input_boolean.enable_hue_motion_sensor_hallway
      state: 'on'
    - condition: template
      value_template: >
        {{ expand(area_entities('sovrum') | select('match', 'light')) | selectattr('state', 'eq', 'on') | list | count == 0 }}
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: 'off'
            - condition: time
              before: '18:00:00'
              after: '09:30:00'
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: 'on'
            - condition: time
              before: '18:00:00'
              after: '07:00:00'
    - condition: template
      value_template: >
        {{ is_state_attr('light.livingroom_couch_table','brightness',255) }}
  actions:
    if:
      condition: state
      entity_id: sun.sun
      state: "below_horizon"
    then:
      action: script.turn_on
      target:
        entity_id: script.bedroom_relaxed
    else:
      action: script.turn_on
      target:
        entity_id: script.bedroom_bright

################# TURN OFF TOP FLOOR LIGHTS NOT IN USE #################

- alias: 'Turn off top floor lights not in use'
  initial_state: true
  triggers:
    trigger: time_pattern
    minutes: "/30"
  conditions:
    - condition: time
      after: '08:00:00'
      before: '18:00:00'
    - or:
      - condition: state
        entity_id: light.hallway_ceiling_top_floor
        state: 'on'
      - condition: state
        entity_id: media_player.girlroom_sonos
        state: 'playing'
    - condition: state
      entity_id:
        - binary_sensor.hallway_top_floor_motion
        - switch.wol_vidar
      state: 'off'
      for: "00:30:00"
    - condition: state
      entity_id: device_tracker.work_laptop
      state: 'not_home'
      for: "00:30:00"
  actions:
    - action: script.turn_on
      target:
        entity_id: script.hallway_bottom_floor_bright
    - action: light.turn_off
      target:
        entity_id: light.bedroom_ceiling

################# MISC #################

- alias: 'Gaming PC turning off'
  initial_state: true
  triggers:
    trigger: state
    entity_id: switch.wol_vidar
    to: 'off'
  conditions:
    - condition: state
      entity_id: light.bedroom_desk
      state: 'on'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
  actions:
    action: script.bedroom_low_brightness

- alias: 'Gaming PC turning on'
  initial_state: true
  triggers:
    trigger: state
    entity_id: switch.wol_vidar
    to: 'on'
  conditions:
    - condition: state
      entity_id: light.bedroom_desk
      state: 'on'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
  actions:
    action: script.bedroom_relaxed

- alias: 'Davids iPhone charging'
  initial_state: true
  triggers:
    trigger: state
    entity_id: sensor.davids_iphone_battery_state
    to: 'Charging'
    for: '00:01:00'
  conditions:
    - condition: time
      after: '22:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: switch.wol_vidar
      state: 'off'
    - condition: state
      entity_id: light.bedroom_desk
      state: 'on'
  actions:
    action: script.bedroom_low_brightness

################# ADVENT LIGHTS #################

- alias: 'Advent lights workday'
  initial_state: true
  triggers:
    trigger: time
    at: '06:45:00'
  conditions:
    - condition: state
      entity_id: input_boolean.enable_advent_light_automations
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  actions:
    action: script.advent_lights_turn_on

- alias: 'Advent lights weekend'
  initial_state: true
  triggers:
    trigger: time
    at: '08:15:00'
  conditions:
    - condition: state
      entity_id: input_boolean.enable_advent_light_automations
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
  actions:
    action: script.advent_lights_turn_on

- alias: 'Livingroom advent light sync'
  initial_state: true
  triggers:
    trigger: state
    entity_id: light.livingroom_window
  conditions:
    condition: state
    entity_id: input_boolean.enable_advent_light_automations
    state: 'on'
  actions:
    choose:
      - conditions: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id:
                - light.livingroom_menorah
                - light.livingroom_christmas_tree
      - conditions: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - action: light.turn_off
            target:
              entity_id:
                - light.livingroom_menorah
                - light.livingroom_christmas_tree

################# CREATE LIGHT GROUPS #################

- alias: 'Create light groups'
  initial_state: true
  triggers:
    trigger: homeassistant
    event: start
  actions:
    - action: script.create_indoor_lights_group
      data:
        exclude_area_id: ['utomhus']
        exclude_entity_id: ['light.boyroom_led_strip']
    - action: script.create_all_lights_group