################# MEDIA #################

- alias: 'Watching TV'
  trigger:
    platform: state
    entity_id: media_player.plex_vardagsrum
    to: 'playing'
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: time
            after: '20:30:00'
          - condition: time
            before: '10:00:00'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-01:00:00'
          - condition: sun
            before: sunrise
            before_offset: '1:00:00'
  action:
    service: script.watching_tv_lights

- alias: 'Decrease child room music volume when turning indoor lights off'
  initial_state: on
  trigger:
    platform: state
    entity_id: script.indoor_lights_off
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
    - condition: state
      entity_id: media_player.childroom_sonos
      state: 'playing'
    - condition: state
      entity_id: binary_sensor.childroom_sonos_is_grouped
      state: 'off'
    - condition: template
      value_template: >
        {{ state_attr('media_player.childroom_sonos','volume_level') > 0.03 }}
  action:
    service: python_script.media_player_volume_set
    data:
      entity_id: media_player.childroom_sonos
      volume_level: 0.03

################# TIMER #################

- alias: 'Kitchen coffee maker timer start'
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.kitchen_coffee_maker
    to: 'on'
  action:
    service: script.kitchen_coffee_maker_timer_start

- alias: 'Kitchen coffee maker timer cancel'
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.kitchen_coffee_maker
    to: 'off'
  condition:
    condition: state
    entity_id: timer.kitchen_coffee_maker
    state: 'active'
  action:
    service: script.kitchen_coffee_maker_timer_cancel