################# CAR HEATER #################

- alias: 'Car heater start'
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.rcb492_heater
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.volvo_rcb492
    state: 'home'
  action:
    service: notify.mobile_app_davids_iphone
    data:
      title: 'Volvo V60'
      message: 'Parkeringsvärmaren har startats'

################# ALARM #################

- alias: 'Alarm not active'
  initial_state: on
  trigger:
    platform: state
    entity_id: group.device_tracker_family
    to: 'not_home'
    for: "00:30:00"
  condition:
    condition: template
    value_template: >
      {{ not is_state('alarm_control_panel.ajax_alarm_status','armed_away') }}
  action:
    choose:
      - conditions: >
          {{ states.device_tracker.davids_iphone.last_changed > states.device_tracker.nellies_iphone.last_changed }}
        sequence:
          - service: notify.mobile_app_davids_iphone
            data:
              message: 'Larmet är ej aktiverat'
              title: 'Larmstatus'
              data:
                sound:
                  name: default
                  critical: 1
                  volume: 0.5
      - conditions: >
          {{ states.device_tracker.davids_iphone.last_changed < states.device_tracker.nellies_iphone.last_changed }}
        sequence:
          - service: notify.mobile_app_nellies_iphone
            data:
              message: 'Larmet är ej aktiverat'
              title: 'Larmstatus'
              data:
                sound:
                  name: default
                  critical: 1
                  volume: 0.5

- alias: 'Night mode not active'
  initial_state: on
  trigger:
    platform: state
    entity_id: script.indoor_lights_off
    to: 'on'
  condition:
    - condition: state
      entity_id: group.device_tracker_family
      state: 'home'
      for: "00:00:05"
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
    - condition: template
      value_template: >
        {{ not is_state('alarm_control_panel.ajax_alarm_status','armed_night') }}
  action:
    service: notify.mobile_app_davids_iphone
    data:
      title: 'Larmstatus'
      message: 'Nattläge är ej aktiverat'
      data:
        sound:
          name: default
          critical: 1
          volume: 0.1