- alias: 'Toggle coffee maker'
  initial_state: on
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: 0AD13D57-0A4F-4973-8908-97A24064DAFE
        actionName: Turn on coffee maker
        sourceDeviceID: davids_iphone
        sourceDeviceName: Davids iPhone
        sourceDevicePermanentID: CFD2DEC1-8CF3-432F-AF78-7419632CC842
        triggerSource: siriShortcut
  action:
    - service: switch.toggle
      target:
        entity_id:
          - switch.kitchen_coffee_maker

- alias: 'Play child room music'
  initial_state: on
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: CADF83CD-087C-4737-8E5F-16D3DB61E40E
        actionName: Play child room music
        sourceDeviceID: davids_iphone
        sourceDeviceName: Davids iPhone
        sourceDevicePermanentID: CFD2DEC1-8CF3-432F-AF78-7419632CC842
        triggerSource: siriShortcut
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionID: 405DCC9E-1D43-4105-9757-390F31263579
        actionName: Play child room music
        sourceDeviceID: nellies_iphone
        sourceDeviceName: Nellies iPhone
        sourceDevicePermanentID: 339E737F-6B8D-4568-8F98-3E422F7E98D8
        triggerSource: siriShortcut
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.childroom_ceiling
          - light.hallway_ceiling_top_floor
          - light.hallway_stair_up
    - choose:
      - conditions: >
          {{ is_state('binary_sensor.childroom_sonos_is_grouped','on') }}
        sequence:
          - service: python_script.media_player_volume_set
            data:
              entity_id: media_player.childroom_sonos
              volume_level: 0
          - service: script.sonos_ungroup_childroom_speaker
          - service: media_player.volume_set
            data:
              entity_id: media_player.childroom_sonos
              volume_level: 0.05
          - delay: '00:00:01'
          - service: media_player.media_play
            target:
              entity_id: media_player.childroom_sonos
      default:
        - service: media_player.volume_set
          data:
            entity_id: media_player.childroom_sonos
            volume_level: 0.05
        - delay: '00:00:01'
        - service: media_player.media_play
          target:
            entity_id: media_player.childroom_sonos