################# HUE  #################

##### LIGHTS #####

- alias: 'Hue switch bright'
  initial_state: on
  triggers:
    trigger: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "short_release"
      subtype: 1
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  actions:
    action: script.bottom_floor_bright

- alias: 'Hue switch relaxed'
  initial_state: on
  triggers:
    trigger: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "long_release"
      subtype: 1
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  actions:
    - action: script.indoor_lights_relaxed
    - condition: state
      entity_id: binary_sensor.childroom_sonos_is_grouped
      state: 'on'
    - action: script.sonos_ungroup_childroom_speaker
    - action: media_player.volume_set
      data:
        entity_id: media_player.childroom_sonos
        volume_level: 0.2

- alias: 'Hue switch turn off lighs'
  initial_state: on
  triggers:
    trigger: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "short_release"
      subtype: 4
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  actions:
    action: script.indoor_lights_off

- alias: 'Hue switch low brightness'
  initial_state: on
  triggers:
    trigger: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "long_release"
      subtype: 4
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  actions:
    action: script.indoor_lights_low_brightness

##### SONOS #####

- alias: 'Hue switch group livingroom speaker'
  initial_state: on
  triggers:
    trigger: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "long_release"
      subtype: 2
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  actions:
    choose:
      - conditions: >
          {{ is_state('binary_sensor.livingroom_sonos_is_grouped','off') }}
        sequence:
          action: script.sonos_group_livingroom_speaker
      - conditions: >
          {{ is_state('binary_sensor.livingroom_sonos_is_grouped','on') }}
        sequence:
          action: script.sonos_ungroup_livingroom_speaker

- alias: 'Hue switch group childroom speaker'
  initial_state: on
  triggers:
    trigger: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "long_release"
      subtype: 3
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  actions:
    choose:
      - conditions: >
          {{ is_state('binary_sensor.childroom_sonos_is_grouped','off') }}
        sequence:
          action: script.sonos_group_childroom_speaker
      - conditions: >
          {{ is_state('binary_sensor.childroom_sonos_is_grouped','on') }}
        sequence:
          action: script.sonos_ungroup_childroom_speaker

- alias: 'Hue switch increase Sonos volume'
  initial_state: on
  triggers:
    trigger: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "short_release"
      subtype: 2
  condition:
    - condition: state
      entity_id: input_boolean.enable_hue_switch_hallway
      state: 'on'
  actions:
    - choose:
        - conditions:
            - condition: state
              entity_id: media_player.kitchen_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.livingroom_apple_tv
              state: 'playing'
            - condition: state
              entity_id: binary_sensor.livingroom_sonos_tv_active
              state: 'on'
          sequence:
            - action: python_script.media_player_volume_set
              data:
                entity_id: media_player.livingroom_sonos
                volume_level: >
                  {{ [((state_attr('media_player.livingroom_sonos','volume_level') | float * 1.15 + 0.03) | round(2)), 1] | min }}
        - conditions:
            - condition: state
              entity_id: media_player.kitchen_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.childroom_sonos
              state: 'playing'
            - condition: state
              entity_id: binary_sensor.childroom_sonos_is_grouped
              state: 'off'
          sequence:
            - action: python_script.media_player_volume_set
              data:
                entity_id: media_player.childroom_sonos
                volume_level: >
                  {{ [((state_attr('media_player.childroom_sonos','volume_level') | float * 1.15 + 0.03) | round(2)), 1] | min }}
      default:
        - action: script.sonos_increase_volume

- alias: 'Hue switch decrease Sonos volume'
  initial_state: on
  triggers:
    trigger: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "short_release"
      subtype: 3
  condition:
    - condition: state
      entity_id: input_boolean.enable_hue_switch_hallway
      state: 'on'
  actions:
    - choose:
        - conditions:
            - condition: state
              entity_id: media_player.kitchen_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.livingroom_apple_tv
              state: 'playing'
            - condition: state
              entity_id: binary_sensor.livingroom_sonos_tv_active
              state: 'on'
          sequence:
            - action: python_script.media_player_volume_set
              data:
                entity_id: media_player.livingroom_sonos
                volume_level: >
                  {{ [((state_attr('media_player.livingroom_sonos','volume_level') | float * 0.85 - 0.03) | round(2)), 0.05] | max }}
        - conditions:
            - condition: state
              entity_id: media_player.kitchen_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.childroom_sonos
              state: 'playing'
            - condition: state
              entity_id: binary_sensor.childroom_sonos_is_grouped
              state: 'off'
          sequence:
            - action: python_script.media_player_volume_set
              data:
                entity_id: media_player.childroom_sonos
                volume_level: >
                  {{ [((state_attr('media_player.childroom_sonos','volume_level') | float * 0.85 - 0.03) | round(2)), 0.05] | max }}
      default:
        - action: script.sonos_decrease_volume

################# IKEA #################

##### BEDROOM #####

- alias: 'Ikea button bedroom on'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 3b531df34853b38343b729aacef15e48
      command: 'on'
  actions:
    action: script.bedroom_relaxed

- alias: 'Ikea button bedroom on long press'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 3b531df34853b38343b729aacef15e48
      command: 'move_with_on_off'
  actions:
    action: script.bedroom_low_brightness

- alias: 'Ikea button bedroom off'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 3b531df34853b38343b729aacef15e48
      command: 'off'
  actions:
    - action: light.turn_off
      target:
        area_id: sovrum

- alias: 'Ikea button bedroom off long press'
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 3b531df34853b38343b729aacef15e48
      command: 'move'
  actions:
    action: script.indoor_lights_off

- alias: 'Ikea styrbar bedroom on'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: f423762e1c28755b0123cc7fd21c5fa7
      command: 'on'
  actions:
    action: script.bedroom_relaxed

- alias: 'Ikea styrbar bedroom on long press'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: f423762e1c28755b0123cc7fd21c5fa7
      command: 'move_with_on_off'
  actions:
    action: script.bedroom_low_brightness

- alias: 'Ikea styrbar bedroom off'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: f423762e1c28755b0123cc7fd21c5fa7
      command: 'off'
  actions:
    - action: light.turn_off
      target:
        area_id: sovrum

- alias: 'Ikea styrbar bedroom off long press'
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: f423762e1c28755b0123cc7fd21c5fa7
      command: 'move'
  actions:
    action: script.indoor_lights_off

- alias: 'Ikea styrbar bedroom increase press'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: f423762e1c28755b0123cc7fd21c5fa7
      command: press
      args: [256, 13, 0]
  actions:
    choose:
      conditions:
        condition: state
        entity_id: light.bedroom_ceiling
        state: 'on'
      sequence:
        action: light.turn_on
        data:
          entity_id: light.bedroom_ceiling
          brightness: >
            {{ [state_attr('light.bedroom_ceiling','brightness') | int + 25, 255] | min }}
    default:
      action: script.bedroom_nursery_light_high

- alias: 'Ikea styrbar bedroom decrease press'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: f423762e1c28755b0123cc7fd21c5fa7
      command: press
      args: [257, 13, 0]
  actions:
    choose:
      conditions:
        condition: state
        entity_id: light.bedroom_ceiling
        state: 'on'
      sequence:
        action: light.turn_on
        data:
          entity_id: light.bedroom_ceiling
          brightness: >
            {{ [state_attr('light.bedroom_ceiling','brightness') | int - 25, 1] | max }}
    default:
      action: script.bedroom_nursery_light

##### CHILD ROOM #####

- alias: 'Ikea button childroom toggle'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'toggle'
  actions:
    action: light.toggle
    data:
      entity_id: light.childroom_ceiling

- alias: 'Ikea button childroom bright'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'step_with_on_off'
  actions:
    action: script.childroom_bright

- alias: 'Ikea button childroom relaxed'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'step'
  actions:
    action: script.childroom_relaxed

- alias: 'Ikea button childroom window light toggle'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'move_with_on_off'
  conditions:
    condition: state
    entity_id: input_boolean.enable_advent_light_automations
    state: 'on'
  actions:
    action: light.toggle
    data:
      entity_id: light.childroom_window

- alias: 'Ikea button childroom led strip disco'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'move_with_on_off'
  conditions:
    condition: state
    entity_id: input_boolean.enable_advent_light_automations
    state: 'off'
  actions:
    - choose:
        - conditions:
            condition: state
            entity_id: light.childroom_led_strip
            state: 'off'
          sequence:
            - action: light.turn_on
              data:
                entity_id: light.childroom_led_strip
                brightness_pct: 100
                effect: 'Random Effect with Custom Values'
            - condition: state
              entity_id: binary_sensor.childroom_sonos_is_grouped
              state: 'on'
            - action: script.turn_on
              target:
                entity_id: script.sonos_ungroup_childroom_speaker
        - conditions:
            condition: state
            entity_id: light.childroom_led_strip
            state: 'on'
          sequence:
            - action: light.turn_off
              target:
                entity_id: light.childroom_led_strip

- alias: 'Ikea button childroom light turn off'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'move'
  actions:
    action: script.childroom_light_dim

- alias: 'Ikea button childroom increase volume'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'press'
      args: [256, 13, 0]
  actions:
    action: python_script.media_player_volume_set
    data:
      entity_id: media_player.childroom_sonos
      volume_level: >
        {{ [((state_attr('media_player.childroom_sonos','volume_level') | float * 1.15 + 0.03) | round(2)), 1] | min }}

- alias: 'Ikea button childroom decrease volume'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'press'
      args: [257, 13, 0]
  actions:
    action: python_script.media_player_volume_set
    data:
      entity_id: media_player.childroom_sonos
      volume_level: >
        {{ [((state_attr('media_player.childroom_sonos','volume_level') | float * 0.85 - 0.03) | round(2)), 0.05] | max }}

- alias: 'Ikea button childroom ungroup speaker'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'hold'
      args: [3329, 0]
  actions:
    action: script.sonos_ungroup_childroom_speaker

- alias: 'Ikea button childroom group speaker'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'hold'
      args: [3328, 0]
  actions:
    action: script.sonos_group_childroom_speaker

##### OFFICE #####

- alias: 'Office switch turn on'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 0e0ddda228abe1831c9056b2834b6454
      command: 'on'
  actions:
    if:
      condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
    then:
      action: script.turn_on
      target:
        entity_id: script.office_bright
    else:
      action: script.turn_on
      target:
        entity_id: script.office_relaxed

- alias: 'Office switch turn off'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 0e0ddda228abe1831c9056b2834b6454
      command: 'off'
  actions:
    action: light.turn_off
    target:
      area_id: arbetsrum

- alias: 'Office switch turn on hold'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 0e0ddda228abe1831c9056b2834b6454
      command: 'move_with_on_off'
  conditions:
    condition: state
    entity_id: binary_sensor.relaxed_mode
    state: 'off'
  actions:
    action: script.turn_on
    target:
      entity_id: script.hallway_top_floor_bright

- alias: 'Office switch turn off hold'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: 0e0ddda228abe1831c9056b2834b6454
      command: 'move'
  actions:
    action: script.turn_on
    target:
      entity_id: script.indoor_lights_low_brightness

##### KITCHEN #####

- alias: 'Ikea switch turn on coffee maker'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: ba91148bbaa6400dc4a15b0b42004ddb
      command: 'on'
  actions:
    - action: switch.turn_on
      target:
        entity_id: switch.kitchen_coffee_maker
    # - action: script.kitchen_coffee_maker_timer_start

- alias: 'Ikea switch turn off coffee maker'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: ba91148bbaa6400dc4a15b0b42004ddb
      command: 'off'
  actions:
    action: switch.turn_off
    target:
      entity_id: switch.kitchen_coffee_maker

- alias: 'Ikea switch turn on kitchen bright'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: ba91148bbaa6400dc4a15b0b42004ddb
      command: 'move_with_on_off'
  actions:
    action: script.kitchen_bright

- alias: 'Ikea switch turn off kitchen lights'
  initial_state: on
  triggers:
    trigger: event
    event_type: zha_event
    event_data:
      device_id: ba91148bbaa6400dc4a15b0b42004ddb
      command: 'move'
  actions:
    action: light.turn_off
    target:
      area_id: kok

################# SHELLY #################

##### LIVINGROOM #####

- alias: 'Shelly livingroom relaxed'
  initial_state: on
  triggers:
    trigger: event
    event_type: shelly.click
    event_data:
      device_id: aad1e36ae5e1a5709dd95de24f0c5fea
      device: shellyswitch25-E098068CEEBD
      channel: 2
      click_type: single
  condition:
    condition: template
    value_template: >
      {{ is_state('light.livingroom_couch_table','on') and not is_state_attr('light.livingroom_couch_table','brightness',76) }}
  actions:
    action: script.livingroom_relaxed

- alias: 'Shelly livingroom bright'
  initial_state: on
  triggers:
    trigger: event
    event_type: shelly.click
    event_data:
      device_id: aad1e36ae5e1a5709dd95de24f0c5fea
      device: shellyswitch25-E098068CEEBD
      channel: 2
      click_type: single
  condition:
    condition: template
    value_template: >
      {{ is_state('light.livingroom_couch_table','off') or is_state_attr('light.livingroom_couch_table','brightness',76) }}
  actions:
    action: script.livingroom_bright

- alias: 'Shelly livingroom relaxed long press'
  initial_state: on
  triggers:
    trigger: event
    event_type: shelly.click
    event_data:
      device_id: aad1e36ae5e1a5709dd95de24f0c5fea
      device: shellyswitch25-E098068CEEBD
      channel: 2
      click_type: long
  condition:
    condition: state
    entity_id: light.livingroom_couch_table
    state: 'off'
  actions:
    action: script.livingroom_relaxed

- alias: 'Shelly livingroom turn off lights'
  initial_state: on
  triggers:
    trigger: event
    event_type: shelly.click
    event_data:
      device_id: aad1e36ae5e1a5709dd95de24f0c5fea
      device: shellyswitch25-E098068CEEBD
      channel: 2
      click_type: long
  condition:
    condition: state
    entity_id: light.livingroom_couch_table
    state: 'on'
  actions:
    - action: light.turn_off
      target:
        area_id: vardagsrum