##### CHILD ROOM #####

- alias: 'Pause bedroom music'
  initial_state: on
  triggers:
    trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.childroom_music
  conditions:
    - condition: state
      entity_id: media_player.childroom_sonos
      state: 'playing'
    - condition: state
      entity_id: binary_sensor.childroom_sonos_is_grouped
      state: 'off'
  actions:
    - action: python_script.media_player_volume_set
      data:
        entity_id: media_player.childroom_sonos
        volume_level: 0.01
    - action: media_player.media_pause
      entity_id: media_player.childroom_sonos
    - action: media_player.volume_set
      data:
        entity_id: media_player.childroom_sonos
        volume_level: 0.10

- alias: 'Start bedroom music timer'
  initial_state: on
  triggers:
    trigger: state
    entity_id: script.indoor_lights_off
    to: 'on'
  conditions:
    - condition: state
      entity_id: media_player.childroom_sonos
      state: 'playing'
    - condition: state
      entity_id: timer.childroom_music
      state: 'idle'
    - condition: state
      entity_id: binary_sensor.childroom_sonos_is_grouped
      state: 'off'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
  actions:
    action: script.bedroom_music_timer_start

##### KITCHEN #####

- alias: 'Kitchen coffee maker timer start'
  triggers:
    - trigger: state
      entity_id: switch.kitchen_coffee_maker
      to: 'on'
      id: "state"
    - trigger: event
      event_type: zha_event
      event_data:
        device_id: ba91148bbaa6400dc4a15b0b42004ddb
        command: 'on'
      id: "remote"
  actions:
    choose:
      - conditions:
          - condition: trigger
            id: "state"
        sequence:
          action: script.kitchen_coffee_maker_timer_start
      - conditions:
        - condition: trigger
          id: "remote"
        - condition: state
          entity_id: switch.kitchen_coffee_maker
          state: 'on'
        sequence:
          action: script.kitchen_coffee_maker_timer_start

- alias: 'Kitchen coffee maker timer cancel'
  initial_state: on
  triggers:
    trigger: state
    entity_id: switch.kitchen_coffee_maker
    to: 'off'
  conditions:
    condition: state
    entity_id: timer.kitchen_coffee_maker
    state: 'active'
  actions:
    action: script.kitchen_coffee_maker_timer_cancel

- alias: 'Timer turn off kitchen coffee maker'
  initial_state: on
  triggers:
    trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen_coffee_maker
  conditions:
    condition: state
    entity_id: switch.kitchen_coffee_maker
    state: 'on'
  actions:
    action: switch.turn_off
    target:
      entity_id: switch.kitchen_coffee_maker

##### BATTERY CHARGING STATION #####

- alias: 'Battery charging station timer start'
  initial_state: on
  triggers:
    trigger: state
    entity_id: switch.battery_charging_station
    to: 'on'
  actions:
    action: timer.start
    data:
      entity_id: timer.battery_charging_station
      duration: '10:00:00'

- alias: 'Battery charging station timer cancel'
  initial_state: on
  triggers:
    trigger: state
    entity_id: switch.battery_charging_station
    from: 'on'
  actions:
    action: timer.cancel
    target:
      entity_id: timer.battery_charging_station

- alias: 'Battery charging station turn off'
  initial_state: on
  triggers:
    trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.battery_charging_station
  actions:
    action: switch.turn_off
    target:
      entity_id: switch.battery_charging_station