################# CAR #################

- alias: 'Car heater started'
  initial_state: on
  triggers:
    trigger: state
    entity_id: switch.sbw57s_heater
    to: 'on'
  conditions:
    - condition: state
      entity_id: device_tracker.sbw57s
      state: 'not_home'
    - condition: state
      entity_id: person.david
      state: 'not_home'
  actions:
    action: notify.mobile_app_davids_iphone
    data:
      title: 'Volvo V60'
      message: 'Klimatanläggning startad'

- alias: 'Car heater audio notification'
  initial_state: on
  triggers:
    trigger: state
    entity_id: switch.sbw57s_heater
    to: 'on'
  conditions:
    - condition: state
      entity_id: device_tracker.sbw57s
      state: 'home'
    - condition: state
      entity_id: person.david
      state: 'home'
  actions:
    action: script.sonos_tts
    data:
      entity_id: media_player.kitchen_sonos
      volume: 0.1
      message: 'Klimatanläggning startad'

- alias: 'Low washer fluid'
  initial_state: on
  triggers:
    trigger: time
    at: '07:00:00'
  conditions:
    condition: state
    entity_id: binary_sensor.volvo_sbw57s_washer_fluid_level_warning
    state: 'on'
  actions:
    action: notify.mobile_app_davids_iphone
    data:
      title: 'Volvo V60'
      message: 'Fyll på spolarvätska'

################# ALARM #################

- alias: 'Alarm not active'
  initial_state: on
  triggers:
    trigger: state
    entity_id: group.device_tracker_family
    to: 'not_home'
    for: "00:30:00"
  conditions:
    condition: template
    value_template: >
      {{ not is_state('alarm_control_panel.ajax_alarm_status','armed_away') }}
  actions:
    choose:
      - conditions: >
          {{ states.person.david.last_changed > states.person.nellie.last_changed }}
        sequence:
          - action: notify.mobile_app_davids_iphone
            data:
              message: 'Larmet är ej aktiverat'
              title: 'Larmstatus'
              data:
                sound:
                  name: default
                  critical: 1
                  volume: 0.5
      - conditions: >
          {{ states.person.david.last_changed < states.person.nellie.last_changed }}
        sequence:
          - action: notify.mobile_app_nellies_iphone
            data:
              message: 'Larmet är ej aktiverat'
              title: 'Larmstatus'
              data:
                sound:
                  name: default
                  critical: 1
                  volume: 0.5

- alias: 'Night mode not active'
  initial_state: on
  triggers:
    trigger: state
    entity_id: script.indoor_lights_off
    to: 'on'
  conditions:
    - condition: state
      entity_id: group.device_tracker_family
      state: 'home'
      for: "00:00:05"
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
    - condition: template
      value_template: >
        {{ not is_state('alarm_control_panel.ajax_alarm_status','armed_night') }}
  actions:
    action: notify.mobile_app_davids_iphone
    data:
      title: 'Larmstatus'
      message: 'Nattläge är ej aktiverat'
      data:
        sound:
          name: default
          critical: 1
          volume: 0.1

##### SHED DOOR #####

- alias: 'Shed door opened not home'
  initial_state: on
  triggers:
    trigger: state
    entity_id: binary_sensor.outdoor_shed_door
    to: 'on'
  conditions:
    - condition: state
      entity_id: alarm_control_panel.ajax_alarm_status
      state: 'armed_away'
    - condition: state
      entity_id: group.device_tracker_family
      state: 'not_home'
  actions:
    action: notify.mobile_app_davids_iphone
    data:
      title: 'Larmstatus'
      message: 'Förrådsdörr öppen'
      data:
        sound:
          name: default
          critical: 1
          volume: 0.5

- alias: 'Shed door opened alarm armed night'
  initial_state: on
  triggers:
    trigger: state
    entity_id: binary_sensor.outdoor_shed_door
    to: 'on'
  conditions:
    condition: state
    entity_id: alarm_control_panel.ajax_alarm_status
    state: 'armed_night'
  actions:
    action: notify.mobile_app_davids_iphone
    data:
      title: 'Larmstatus'
      message: 'Förrådsdörr öppen'
      data:
        sound:
          name: default
          critical: 1
          volume: 0.5

- alias: 'Shed door open alarm armed night activated'
  initial_state: on
  triggers:
    trigger: state
    entity_id: alarm_control_panel.ajax_alarm_status
    to: 'armed_night'
  conditions:
    condition: state
    entity_id: binary_sensor.outdoor_shed_door
    state: 'on'
  actions:
    action: notify.mobile_app_davids_iphone
    data:
      title: 'Larmstatus'
      message: 'Förrådsdörr öppen'
      data:
        sound:
          name: default
          critical: 1
          volume: 0.1

################# CCTV #################

##### OUTDOOR PORCH #####

- alias: 'Person detected notify Davids iPhone'
  triggers:
    trigger: state
    entity_id: sensor.asgari_1_person_count
  conditions:
    condition: template
    value_template: '{{ trigger.to_state.state | int > trigger.from_state.state | int }}'
  actions:
    action: notify.mobile_app_davids_iphone
    data:
      title: 'Övervakningskamera'
      message: 'Person detekterad'
      data:
        url: "/lovelace/2"
        push:
          sound:
            name: US-EN-Morgan-Freeman-Motion-Detected.wav
            critical: 1
            volume: 0.8

- alias: 'Person detected notify Nellies iPhone'
  triggers:
    trigger: state
    entity_id: sensor.asgari_1_person_count
  conditions:
    condition: template
    value_template: '{{ trigger.to_state.state | int > trigger.from_state.state | int }}'
  actions:
    action: notify.mobile_app_nellies_iphone
    data:
      title: 'Övervakningskamera'
      message: 'Person detekterad'
      data:
        url: "/lovelace/2"
        push:
          sound:
            name: US-EN-Morgan-Freeman-Motion-Detected.wav
            critical: 1
            volume: 0.8

- alias: 'Person detected notify Sonos'
  triggers:
    trigger: state
    entity_id: sensor.asgari_1_person_count
  conditions:
    condition: template
    value_template: '{{ trigger.to_state.state | int > trigger.from_state.state | int }}'
  actions:
    action: script.sonos_play_local_media
    data:
      entity_id: media_player.livingroom_sonos
      media_filename: "US-EN-Morgan-Freeman-Motion-Detected.mp3"
      volume: 0.3

##### CHILD ROOM #####

- alias: 'Sound detected notify Davids iPhone'
  triggers:
    - trigger: state
      entity_id: binary_sensor.deltaco_1_child_singing_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_crying_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_humming_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_scream_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_humming_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_singing_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_whispering_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_yell_sound
      to: 'on'
  actions:
    action: notify.mobile_app_davids_iphone
    data:
      title: 'Barnrum'
      message: 'Ljud detekterat'
      data:
        url: "/lovelace/2"
        push:
          sound:
            name: "WebcamStart.caf"
            critical: 1
            volume: 0.8

- alias: 'Sound detected notify Nellies iPhone'
  triggers:
    - trigger: state
      entity_id: binary_sensor.deltaco_1_child_singing_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_crying_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_humming_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_scream_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_humming_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_singing_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_whispering_sound
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.deltaco_1_yell_sound
      to: 'on'
  actions:
    action: notify.mobile_app_nellies_iphone
    data:
      title: 'Barnrum'
      message: 'Ljud detekterat'
      data:
        url: "/lovelace/2"
        push:
          sound:
            name: "WebcamStart.caf"
            critical: 1
            volume: 0.8

################# TRAEFIK STATUS #################

- alias: 'Web service down'
  initial_state: on
  triggers:
    trigger: time_pattern
    minutes: "/10"
  conditions:
    not:
      - condition: state
        entity_id:
          - sensor.docker_traefik_state
          - sensor.docker_authelia_state
          - sensor.docker_mariadb_state
          - sensor.docker_wordpress_state
        state: 'running'
      - condition: time
        after: "04:00:00"
        before: "05:00:00"
        weekday: sun
  actions:
    action: notify.mobile_app_davids_iphone
    data:
      title: 'Web service status'
      message: 'A web service is down'
      data:
        url: "/lovelace/6"