- alias: 'Leaving home'
  initial_state: on
  triggers:
    trigger: state
    entity_id: group.device_tracker_family
    to: 'not_home'
  actions:
    action: script.indoor_lights_off

- alias: 'Coming home turn on lights bright'
  initial_state: on
  triggers:
    - trigger: state
      entity_id: group.device_tracker_family
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.coming_home_turn_on_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
    - condition: sun
      after: sunset
      after_offset: '-01:00:00'
    - condition: or
      conditions:
        - condition: state
          entity_id: group.indoor_lights
          state: 'off'
        - condition: state
          entity_id: input_boolean.away_lights_active
          state: 'on'
  actions:
    - action: script.bottom_floor_bright
    - action: input_boolean.turn_off
      data:
        entity_id: input_boolean.away_lights_active
    - condition: state
      entity_id: input_boolean.enable_advent_light_automations
      state: 'on'
    - action: script.turn_on
      target:
        entity_id:
          - script.bedroom_advent_lights
          - script.office_advent_lights
          - script.childroom_advent_lights

- alias: 'Coming home turn on lights relaxed'
  initial_state: on
  triggers:
    - trigger: state
      entity_id: group.device_tracker_family
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.coming_home_turn_on_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
    - condition: sun
      after: sunset
      after_offset: '-01:00:00'
    - condition: or
      conditions:
        - condition: state
          entity_id: group.indoor_lights
          state: 'off'
        - condition: state
          entity_id: input_boolean.away_lights_active
          state: 'on'
  actions:
    - action: script.indoor_lights_relaxed
    - action: input_boolean.turn_off
      data:
        entity_id: input_boolean.away_lights_active

- alias: 'Coming home turn on hallway lights'
  initial_state: on
  triggers:
    - trigger: state
      entity_id: group.device_tracker_family
      to: 'home'
    - trigger: state
      entity_id: person.nellie
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.coming_home_turn_on_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
    - condition: sun
      before: sunset
      before_offset: '-01:00:00'
    - condition: or
      conditions:
        - condition: state
          entity_id: group.indoor_lights
          state: 'off'
        - condition: state
          entity_id: device_tracker.sela_lt6ywwb54
          state: 'home'
        - condition: state
          entity_id: input_boolean.away_lights_active
          state: 'on'
  actions:
    - action: script.hallway_bright
    - action: input_boolean.turn_off
      data:
        entity_id: input_boolean.away_lights_active
    - condition: state
      entity_id: input_boolean.enable_advent_light_automations
      state: 'on'
    - action: script.advent_lights_turn_on

- alias: 'Coming home group Sonos speakers'
  initial_state: on
  triggers:
    trigger: state
    entity_id: group.device_tracker_family
    to: 'home'
  condition:
    condition: state
    entity_id: binary_sensor.livingroom_sonos_tv_active
    state: 'off'
  actions:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.relaxed_mode
              state: 'on'
          sequence:
            - action: script.sonos_group_livingroom_speaker
            - action: script.sonos_set_group_volume
              data:
                volume: 0.2
            - action: script.sonos_ungroup_childroom_speaker
            - action: media_player.volume_set
              data:
                entity_id: media_player.childroom_sonos
                volume_level: 0.2
      default:
        - action: script.sonos_group_all_speakers
        - action: script.sonos_set_group_volume
          data:
            volume: 0.2

################# SONOS #################

- alias: 'Start working'
  initial_state: on
  triggers:
    trigger: state
    entity_id: device_tracker.sela_lt6ywwb54
    to: 'home'
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: time
      before: '17:00:00'
  actions:
    - action: script.office_bright
    - action: script.hallway_top_floor_bright
    - action: script.sonos_ungroup_childroom_speaker
    - action: media_player.volume_set
      data:
        entity_id: media_player.childroom_sonos
        volume_level: 0.40
    - condition: state
      entity_id: person.nellie
      state: 'not_home'
    - action: light.turn_off
      target:
        entity_id: 
        - light.hallway_ceiling_bottom_floor
        - light.kitchen_table
        - light.livingroom_couch_table
        - light.livingroom_dinner_table
        - light.livingroom_floor
        - light.livingroom_window
        - light.bedroom_bedside
        - light.childroom_ceiling
    - action: script.sonos_ungroup_childroom_speaker

- alias: 'Stop working'
  initial_state: on
  triggers:
    trigger: state
    entity_id: device_tracker.sela_lt6ywwb54
    to: 'not_home'
  actions:
    action: light.turn_off
    target:
      entity_id: light.office_ceiling

- alias: 'Leaving home during work hours'
  initial_state: on
  triggers:
    trigger: state
    entity_id: person.david
    to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.sela_lt6ywwb54
      state: 'home'
    - condition: state
      entity_id: person.nellie
      state: 'home'
  actions:
    action: light.turn_off
    target:
      area_id: arbetsrum

- alias: 'Coming home during work hours'
  initial_state: on
  triggers:
    trigger: state
    entity_id: device_tracker.davids_iphone
    to: 'home'
  condition:
    condition: state
    entity_id: device_tracker.sela_lt6ywwb54
    state: 'home'
  actions:
    action: script.office_bright

- alias: 'Nellie leaving home during work hours'
  initial_state: on
  triggers:
    trigger: state
    entity_id: person.nellie
    to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.sela_lt6ywwb54
      state: 'home'
    - condition: state
      entity_id: person.david
      state: 'home'
  actions:
    - action: light.turn_off
      target:
        entity_id:
          - light.hallway_ceiling_bottom_floor
          - light.hallway_stair_group
        area_id:
          - kok
          - vardagsrum
          - sovrum
          - barnrum
    - condition: state
      entity_id: media_player.kitchen_sonos
      state: 'playing'
    - action: media_player.media_pause
      target:
        entity_id: media_player.kitchen_sonos