################# TIME #################

- alias: 'Evening bright'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    - condition: state
      entity_id: group.device_tracker_family
      state: 'home'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
    - condition: time
      before: '19:00:00'
  action:
    service: script.bottom_floor_bright

- alias: 'Evening relaxed'
  trigger:
    platform: state
    entity_id: binary_sensor.relaxed_mode
    to: 'on'
  condition:
    condition: state
    entity_id: group.device_tracker_family
    state: 'home'
  action:
    - service: script.indoor_lights_relaxed
    - condition: state
      entity_id: binary_sensor.childroom_sonos_is_grouped
      state: 'on'
    - service: script.sonos_ungroup_childroom_speaker
    - condition: template
      value_template: >
        {{ state_attr('media_player.childroom_sonos','volume_level') > 0.10 }}
    - service: media_player.volume_set
      data:
        entity_id: media_player.childroom_sonos
        volume_level: 0.10

- alias: 'Hallway bright'
  trigger:
    platform: time
    at: '09:00:00'
  condition:
    condition: state
    entity_id: group.device_tracker_family
    state: 'home'
  action:
    service: script.hallway_bright

- alias: 'Child room night light'
  trigger:
    platform: time
    at: '21:30:00'
  action:
    service: script.childroom_night_light

- alias: 'Child room morning play light'
  trigger:
    platform: time
    at: '06:00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.childroom_led_strip
      brightness_pct: 30
      rgb_color: [0,255,0]
      transition: 2
      effect: None

- alias: 'Child room morning wakeup light'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.childroom_led_strip
      brightness_pct: 35
      rgb_color: [0,0,255]
      transition: 2
      effect: None

- alias: 'Advent lights workday'
  initial_state: on
  trigger:
    platform: time
    at: '06:45:00'
  condition:
    - condition: state
      entity_id: input_boolean.enable_advent_light_automations
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    service: script.advent_lights_turn_on

- alias: 'Advent lights weekend'
  initial_state: on
  trigger:
    platform: time
    at: '08:15:00'
  condition:
    - condition: state
      entity_id: input_boolean.enable_advent_light_automations
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
  action:
    service: script.advent_lights_turn_on

################# SUNSET/SUNRISE #################

- alias: 'Sunset'
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: group.device_tracker_family
      state: 'home'
    - condition: state
      entity_id: group.indoor_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
  action:
    service: script.turn_on
    target:
      entity_id: script.window_lights

- alias: 'Bright after sunset bedroom'
  initial_state: off
  trigger:
    platform: state
    entity_id: script.bedroom_bright
    to: 'on'
  condition:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: input_boolean.window_lights_after_sunset
      state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_bedside
      brightness_pct: 100

- alias: 'Bright after sunset livingroom'
  initial_state: on
  trigger:
    platform: state
    entity_id: script.livingroom_bright
    to: 'on'
  condition:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: input_boolean.window_lights_after_sunset
      state: 'on'
  action:
    service: light.turn_on
    target:
      entity_id:
        - light.livingroom_window
        - light.office_window

- alias: 'Outdoor lights at sunset'
  initial_state: on
  trigger:
    platform: sun
    event: sunset
    offset: "00:05:00"
  action:
    service: script.turn_on_outdoor_lights

- alias: 'Outdoor lights at sunrise'
  initial_state: on
  trigger:
    platform: sun
    event: sunrise
  action:
    service: script.turn_off_outdoor_lights

- alias: 'Outdoor lights when sun above horizon'
  initial_state: on
  trigger:
    platform: time_pattern
    minutes: "/30"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"
    - condition: state
      entity_id:
        - light.outdoor_main_entrance
        - light.outdoor_porch
      match: any
      state: 'on'
  action:
    - service: script.turn_off_outdoor_lights

- alias: 'Turn off child room night light at sunrise'
  initial_state: on
  trigger:
    platform: sun
    event: sunrise
    offset: '02:00:00'
  action:
    service: light.turn_off
    target:
      entity_id: light.childroom_led_strip

################# WAKEUP/BED #################

- alias: 'Wakeup weekdays'
  trigger:
    platform: template
    value_template: >
      {{ now() >= today_at(states('input_datetime.wakeup_weekdays')) - timedelta(minutes = 30) }}
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.wakeup_override
        state: 'on'
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
          - condition: state
            entity_id: group.device_tracker_family
            state: 'home'
  action:
    service: script.wakeup_lights

- alias: 'Wakeup weekend'
  trigger:
    platform: template
    value_template: >
      {{ now() >= today_at(states('input_datetime.wakeup_weekend')) - timedelta(minutes = 30) }}
  condition:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: group.device_tracker_family
      state: 'home'
  action:
    service: script.wakeup_lights

- alias: 'Go to bed weekdays'
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor_offset
    state: 'on'
  action:
    service: script.go_to_bed_lights

- alias: 'Go to bed weekend'
  trigger:
    platform: time
    at: '23:59:00'
  condition:
    condition: time
    weekday:
      - fri
      - sat
  action:
    service: script.go_to_bed_lights

################# AWAY #################

- alias: 'Away turn on lights'
  initial_state: on
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: input_boolean.enable_away_lights
      state: 'on'
    - condition: state
      entity_id: group.device_tracker_family
      state: 'not_home'
  action:
    - service: script.enable_away_lights
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.away_lights_active

- alias: 'Leaving home turn on lights'
  initial_state: on
  trigger:
    platform: state
    entity_id: group.device_tracker_family
    to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.enable_away_lights
      state: 'on'
    - condition: sun
      after: sunset
  action:
    - service: script.enable_away_lights
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.away_lights_active

- alias: 'Away turn off lights'
  initial_state: on
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    - condition: state
      entity_id: group.device_tracker_family
      state: 'not_home'
    - condition: state
      entity_id: group.indoor_lights
      state: 'on'
  action:
    - service: script.indoor_lights_off
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.away_lights_active

################# BATHROOM #################

- alias: 'Increase bathroom ceiling light brightness'
  initial_state: on
  trigger:
    platform: state
    entity_id: light.bathroom_ceiling
    to: 'on'
  condition:
    - condition: template
      value_template: >
        {{ state_attr('light.bathroom_ceiling','brightness') < 255 }}
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom_ceiling
      brightness_pct: 100

################# MOTION SENSOR #################

- alias: 'Hallway top floor motion hallway bright'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_top_floor_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.enable_hue_motion_sensor_hallway
      state: 'on'
    - condition: state
      entity_id: light.hallway_ceiling_top_floor
      state: 'off'
    - condition: time
      before: '18:00:00'
      after: '07:00:00'
    - condition: template
      value_template: >
        {{ is_state_attr('light.hallway_ceiling_bottom_floor','brightness',255) }}
    - condition: template
      value_template: >
        {{ not (is_state('binary_sensor.childroom_sonos_is_grouped','off') and is_state('media_player.childroom_sonos','playing')) }}
  action:
    service: script.hallway_top_floor_bright

- alias: 'Hallway top floor motion rooms bright'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_top_floor_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.enable_hue_motion_sensor_hallway
      state: 'on'
    - condition: state
      entity_id: light.office_ceiling
      state: 'off'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'off'
    - condition: or
      conditions:
        - condition: time
          weekday:
            - sat
            - sun
          after: '09:30:00'
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: 'on'
            - condition: time
              after: '07:00:00'
    - condition: template
      value_template: >
        {{ is_state_attr('light.livingroom_couch_table','brightness',255) }}
  action:
    - service: script.turn_on
      target:
        entity_id: script.office_bright
    # - condition: time
    #   before: '11:00:00'
    #   after: '16:00:00'
    # - condition: template
    #   value_template: >
    #     {{ not (is_state('binary_sensor.childroom_sonos_is_grouped','off') and is_state('media_player.childroom_sonos','playing')) }}
    # - service: script.turn_on
    #   target:
    #     entity_id:
    #       - script.childroom_bright

################# TURN OFF TOP FLOOR LIGHTS NOT IN USE #################

- alias: 'Turn off top floor lights not in use'
  initial_state: on
  trigger:
    platform: time_pattern
    minutes: "/30"
  condition:
    - condition: time
      after: '08:00:00'
      before: '18:00:00'
    - or:
      - condition: state
        entity_id: light.hallway_ceiling_top_floor
        state: 'on'
      - condition: state
        entity_id: media_player.childroom_sonos
        state: 'playing'
    - condition: state
      entity_id:
        - binary_sensor.hallway_top_floor_motion
        - switch.wol_vidar
      state: 'off'
      for: "00:30:00"
    - condition: state
      entity_id: device_tracker.sela_ltjs4sl13
      state: 'not_home'
      for: "00:30:00"
  action:
    - service: script.turn_on
      target:
        entity_id: script.hallway_bottom_floor_bright
    - service: light.turn_off
      target:
        entity_id:
          - light.office_ceiling
          - light.childroom_ceiling

################# MISC #################

- alias: 'Tor turning off'
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.wol_vidar
    to: 'off'
  condition:
    - condition: state
      entity_id: light.office_desk
      state: 'on'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
  action:
    service: script.office_low_brightness

- alias: 'Tor turning on'
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.wol_vidar
    to: 'on'
  condition:
    - condition: state
      entity_id: light.office_desk
      state: 'on'
    - condition: state
      entity_id: binary_sensor.relaxed_mode
      state: 'on'
  action:
    service: script.office_relaxed

- alias: 'Davids iPhone charging'
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.davids_iphone_battery_state
    to: 'Charging'
    for: '00:01:00'
  condition:
    - condition: time
      after: '22:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: switch.wol_vidar
      state: 'off'
    - condition: state
      entity_id: light.office_desk
      state: 'on'
  action:
    service: script.office_low_brightness

################# CREATE LIGHT GROUPS #################

- alias: 'Create light groups'
  initial_state: on
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.create_indoor_lights_group
      data:
        exclude_area_id: ['utomhus']
        exclude_entity_id: ['light.childroom_led_strip']
    - service: script.create_all_lights_group