- alias: 'Toggle coffee maker'
  initial_state: true
  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionID: 0AD13D57-0A4F-4973-8908-97A24064DAFE
        actionName: Turn on coffee maker
        sourceDeviceID: davids_iphone
        sourceDeviceName: Davids iPhone
        sourceDevicePermanentID: CFD2DEC1-8CF3-432F-AF78-7419632CC842
        triggerSource: appShortcut
  actions:
    - action: switch.toggle
      target:
        entity_id: switch.kitchen_coffee_maker

- alias: 'Play child room music'
  initial_state: true
  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionID: CADF83CD-087C-4737-8E5F-16D3DB61E40E
        actionName: Play child room music
        sourceDeviceID: davids_iphone
        sourceDeviceName: Davids iPhone
        sourceDevicePermanentID: CFD2DEC1-8CF3-432F-AF78-7419632CC842
        triggerSource: appShortcut
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionID: 405DCC9E-1D43-4105-9757-390F31263579
        actionName: Play child room music
        sourceDeviceID: nellies_iphone
        sourceDeviceName: Nellies iPhone
        sourceDevicePermanentID: 339E737F-6B8D-4568-8F98-3E422F7E98D8
        triggerSource: appShortcut
  actions:
    - action: light.turn_off
      target:
        entity_id:
          - light.girlroom_ceiling
          - light.hallway_ceiling_top_floor
          - light.hallway_stair_up
    - action: script.turn_on
      target:
        entity_id: script.play_girlroom_night_music

- alias: 'Turn on PC'
  initial_state: true
  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionID: 184A8E4A-CE5B-4B01-B015-7A54F99814F3
        actionName: Turn on PC
        sourceDeviceID: davids_iphone
        sourceDeviceName: Davids iPhone
        sourceDevicePermanentID: CFD2DEC1-8CF3-432F-AF78-7419632CC842
        triggerSource: appShortcut
  actions:
    - action: switch.turn_on
      target:
        entity_id: switch.wol_vidar