################# HUE  #################

##### LIGHTS #####

- alias: 'Hue switch bright'
  initial_state: on
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "short_release"
      subtype: 1
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  action:
    service: script.bottom_floor_bright

- alias: 'Hue switch relaxed'
  initial_state: on
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "long_release"
      subtype: 1
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  action:
    - service: script.indoor_lights_relaxed
    - condition: state
      entity_id: binary_sensor.childroom_sonos_is_grouped
      state: 'on'
    - service: script.sonos_ungroup_childroom_speaker
    - service: media_player.volume_set
      data:
        entity_id: media_player.childroom_sonos
        volume_level: 0.2

- alias: 'Hue switch turn off lighs'
  initial_state: on
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "short_release"
      subtype: 4
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  action:
    service: script.indoor_lights_off

- alias: 'Hue switch low brightness'
  initial_state: on
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "long_release"
      subtype: 4
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  action:
    service: script.indoor_lights_low_brightness

##### SONOS #####

- alias: 'Hue switch group livingroom speaker'
  initial_state: on
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "long_release"
      subtype: 2
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  action:
    choose:
      - conditions: >
          {{ is_state('binary_sensor.livingroom_sonos_is_grouped','off') }}
        sequence:
          service: script.sonos_group_livingroom_speaker
      - conditions: >
          {{ is_state('binary_sensor.livingroom_sonos_is_grouped','on') }}
        sequence:
          service: script.sonos_ungroup_livingroom_speaker

- alias: 'Hue switch group childroom speaker'
  initial_state: on
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "long_release"
      subtype: 3
  condition:
    condition: state
    entity_id: input_boolean.enable_hue_switch_hallway
    state: 'on'
  action:
    choose:
      - conditions: >
          {{ is_state('binary_sensor.childroom_sonos_is_grouped','off') }}
        sequence:
          service: script.sonos_group_childroom_speaker
      - conditions: >
          {{ is_state('binary_sensor.childroom_sonos_is_grouped','on') }}
        sequence:
          service: script.sonos_ungroup_childroom_speaker

- alias: 'Hue switch increase Sonos volume'
  initial_state: on
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "short_release"
      subtype: 2
  condition:
    - condition: state
      entity_id: input_boolean.enable_hue_switch_hallway
      state: 'on'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: media_player.kitchen_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.childroom_sonos
              state: 'playing'
            - condition: state
              entity_id: binary_sensor.childroom_sonos_is_grouped
              state: 'off'
          sequence:
            - service: python_script.media_player_volume_set
              data:
                entity_id: media_player.childroom_sonos
                volume_level: >
                  {{ [((state_attr('media_player.childroom_sonos','volume_level') | float * 1.15 + 0.03) | round(2)), 1] | min }}
        - conditions:
            - condition: state
              entity_id: media_player.kitchen_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.childroom_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.livingroom_apple_tv
              state: 'playing'
            - condition: state
              entity_id: binary_sensor.livingroom_sonos_tv_active
              state: 'on'
          sequence:
            - service: python_script.media_player_volume_set
              data:
                entity_id: media_player.livingroom_sonos
                volume_level: >
                  {{ [((state_attr('media_player.livingroom_sonos','volume_level') | float * 1.15 + 0.03) | round(2)), 1] | min }}
      default:
        - service: script.sonos_increase_volume

- alias: 'Hue switch decrease Sonos volume'
  initial_state: on
  trigger:
    platform: event
    event_type: hue_event
    event_data:
      id: "hallway_switch_button"
      type: "short_release"
      subtype: 3
  condition:
    - condition: state
      entity_id: input_boolean.enable_hue_switch_hallway
      state: 'on'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: media_player.kitchen_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.childroom_sonos
              state: 'playing'
            - condition: state
              entity_id: binary_sensor.childroom_sonos_is_grouped
              state: 'off'
          sequence:
            - service: python_script.media_player_volume_set
              data:
                entity_id: media_player.childroom_sonos
                volume_level: >
                  {{ [((state_attr('media_player.childroom_sonos','volume_level') | float * 0.85 - 0.03) | round(2)), 0.05] | max }}
        - conditions:
            - condition: state
              entity_id: media_player.kitchen_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.childroom_sonos
              state:
                - 'paused'
                - 'idle'
            - condition: state
              entity_id: media_player.livingroom_apple_tv
              state: 'playing'
            - condition: state
              entity_id: binary_sensor.livingroom_sonos_tv_active
              state: 'on'
          sequence:
            - service: python_script.media_player_volume_set
              data:
                entity_id: media_player.livingroom_sonos
                volume_level: >
                  {{ [((state_attr('media_player.livingroom_sonos','volume_level') | float * 0.85 - 0.03) | round(2)), 0.05] | max }}
      default:
        - service: script.sonos_decrease_volume

################# IKEA #################

##### BEDROOM #####

- alias: 'Ikea button bedroom on'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 3b531df34853b38343b729aacef15e48
      command: 'on'
  action:
    service: script.bedroom_relaxed

- alias: 'Ikea button bedroom on long press'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 3b531df34853b38343b729aacef15e48
      command: 'move_with_on_off'
  action:
    service: script.bedroom_low_brightness

- alias: 'Ikea button bedroom off'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 3b531df34853b38343b729aacef15e48
      command: 'off'
  action:
    - service: light.turn_off
      target:
        area_id: sovrum

- alias: 'Ikea button bedroom off long press'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 3b531df34853b38343b729aacef15e48
      command: 'move'
  action:
    service: script.indoor_lights_off

##### CHILD ROOM #####

- alias: 'Ikea button childroom toggle'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'toggle'
  action:
    service: light.toggle
    data:
      entity_id: light.childroom_ceiling

- alias: 'Ikea button childroom bright'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'step_with_on_off'
  action:
    service: script.childroom_bright

- alias: 'Ikea button childroom relaxed'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'step'
  action:
    service: script.childroom_relaxed

- alias: 'Ikea button childroom light warm'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'move_with_on_off'
  action:
    service: script.childroom_light_warm

- alias: 'Ikea button childroom light turn off'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'move'
  action:
    service: script.childroom_light_dim

- alias: 'Ikea button childroom increase volume'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'press'
      args: [256, 13, 0]
  action:
    service: python_script.media_player_volume_set
    data:
      entity_id: media_player.childroom_sonos
      volume_level: >
        {{ [((state_attr('media_player.childroom_sonos','volume_level') | float * 1.15 + 0.03) | round(2)), 1] | min }}

- alias: 'Ikea button childroom decrease volume'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'press'
      args: [257, 13, 0]
  action:
    service: python_script.media_player_volume_set
    data:
      entity_id: media_player.childroom_sonos
      volume_level: >
        {{ [((state_attr('media_player.childroom_sonos','volume_level') | float * 0.85 - 0.03) | round(2)), 0.05] | max }}

- alias: 'Ikea button childroom ungroup speaker'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'hold'
      args: [3329, 0]
  action:
    service: script.sonos_ungroup_childroom_speaker

- alias: 'Ikea button childroom group speaker'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 44bc2855a0757d86e2bf3ca19df7db77
      command: 'hold'
      args: [3328, 0]
  action:
    service: script.sonos_group_childroom_speaker

##### OFFICE #####

- alias: 'Ikea switch turn on Vidar'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 9f686575e6ad98784e2efbb0b4e78526
      command: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.wol_vidar

# - alias: 'Ikea switch turn off indoor lights'
#   initial_state: on
#   trigger:
#     platform: event
#     event_type: zha_event
#     event_data:
#       device_id: 9f686575e6ad98784e2efbb0b4e78526
#       command: 'off'
#   action:
#     service: script.indoor_lights_off

##### KITCHEN #####

- alias: 'Ikea switch turn on coffee maker'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 0e0ddda228abe1831c9056b2834b6454
      command: 'on'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.kitchen_coffee_maker
    # - service: script.kitchen_coffee_maker_timer_start

- alias: 'Ikea switch turn off coffee maker'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 0e0ddda228abe1831c9056b2834b6454
      command: 'off'
  action:
    service: switch.turn_off
    target:
      entity_id: switch.kitchen_coffee_maker

- alias: 'Ikea switch turn on kitchen bright'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 0e0ddda228abe1831c9056b2834b6454
      command: 'move_with_on_off'
  action:
    service: script.kitchen_bright

- alias: 'Ikea switch turn off kitchen lights'
  initial_state: on
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 0e0ddda228abe1831c9056b2834b6454
      command: 'move'
  action:
    service: light.turn_off
    target:
      entity_id: light.kitchen_table

################# SHELLY #################

##### LIVINGROOM #####

- alias: 'Shelly livingroom relaxed'
  initial_state: on
  trigger:
    platform: event
    event_type: shellyforhass.click
    event_data:
      entity_id: binary_sensor.livingroom_shelly_2_switch
      click_type: single
  condition:
    condition: template
    value_template: >
      {{ is_state('light.livingroom_couch_table','on') and not is_state_attr('light.livingroom_couch_table','brightness',76) }}
  action:
    service: script.livingroom_relaxed

- alias: 'Shelly livingroom bright'
  initial_state: on
  trigger:
    platform: event
    event_type: shellyforhass.click
    event_data:
      entity_id: binary_sensor.livingroom_shelly_2_switch
      click_type: single
  condition:
    condition: template
    value_template: >
      {{ is_state('light.livingroom_couch_table','off') or is_state_attr('light.livingroom_couch_table','brightness',76) }}
  action:
    service: script.livingroom_bright

- alias: 'Shelly livingroom relaxed long press'
  initial_state: on
  trigger:
    platform: event
    event_type: shellyforhass.click
    event_data:
      entity_id: binary_sensor.livingroom_shelly_2_switch
      click_type: long
  condition:
    condition: state
    entity_id: light.livingroom_couch_table
    state: 'off'
  action:
    service: script.livingroom_relaxed

- alias: 'Shelly livingroom turn off lights'
  initial_state: on
  trigger:
    platform: event
    event_type: shellyforhass.click
    event_data:
      entity_id: binary_sensor.livingroom_shelly_2_switch
      click_type: long
  condition:
    condition: state
    entity_id: light.livingroom_couch_table
    state: 'on'
  action:
    - service: light.turn_off
      target:
        area_id: vardagsrum